# -*- coding: utf-8 -*-
import re
from pathlib import Path

BASE = Path(__file__).resolve().parent / "external_links"

PHRASE_FIXES = {
    # Cụm phổ biến trong kenshi_opening/status/blessing/camp/base/fight.
    "雇佣": "đánh thuê",
    "雇佣兵": "lính đánh thuê",
    "虚伪": "giả dối",
    "颤抖": "run rẩy",
    "瑟瑟发抖": "run lẩy bẩy",
    "瑟瑟": "run lẩy bẩy",
    "渣滓": "cặn bã",
    "驱逐": "trục xuất",
    "牺牲": "hy sinh",
    "哔噗": "Beep",
    "艾露": "Ailu",
    "推荐": "đề xuất",
    "怜悯": "thương xót",
    "污秽": "ô uế",
    "坏牙": "Răng Hỏng",
    "均衡": "cân bằng",
    "恐怖": "kinh hoàng",
    "沸腾": "sôi sục",
    "必须": "bắt buộc",
    "忏悔": "sám hối",
    "敬畏": "kính sợ",
    "肥沃": "màu mỡ",
    "诅咒": "nguyền rủa",
    "积蓄": "tiền tích cóp",
    "协助": "hỗ trợ",
    "历史": "lịch sử",
    "愉悦": "vui sướng",
    "苏醒": "thức tỉnh",
    "苟延": "thoi thóp",
    "苟延残喘": "thoi thóp kéo dài hơi tàn",
    "逐渐": "dần dần",
    "枢纽": "Hub",
    "免疫": "miễn nhiễm",
    "休眠": "ngủ đông",
    "温顺": "hiền lành",
    "蜥蜴": "thằn lằn",
    "赋予": "ban cho",
    "掉啦": "rơi rồi",
    "苏丹": "Sultan",
    "纯粹": "thuần túy",
    "束缚": "trói buộc",
    "忠诚": "trung thành",
    "愤怒": "giận dữ",
    "延伸": "phần nối dài",
    "葡萄": "nho",
    "葡萄酒": "rượu nho",
    "百倍": "gấp trăm lần",
    "骄傲": "kiêu hãnh",
    "漂泊": "phiêu bạt",
    "弥漫": "lan tràn",
    "病患": "bệnh nhân",
    "呼吸": "hít thở",
    "燃烧": "bốc cháy",
    "咆哮": "gầm rú",
    "广袤": "rộng mênh mông",
    "蜘蛛": "nhện",
    "哀嚎": "gào thét",
    "恐惧": "sợ hãi",
    "侦察": "trinh sát",
    "侦查": "trinh sát",
    "长途跋涉": "băng qua đường dài",
    "途跋涉": "băng đường dài",
    "滤镜": "bộ lọc",
    "敏锐": "nhạy bén",
    "阅读": "đọc",
    "帷幕": "màn che",
    "屠宰": "giết mổ",
    "阴影": "bóng tối",
    "蕾丝": "ren",
    "犀牛": "tê giác",
    "哈希": "Hash",
    "跟踪": "theo dõi",
    "哈兹姆": "Hazm",
    "阴谋": "âm mưu",
    "脖颈": "cổ",
    "镣铐": "xiềng xích",
    "巅峰": "đỉnh cao",
    "嘶吼": "gầm rống",
    "朴素": "mộc mạc",
    "虔诚": "thành kính",
    "尊敬": "kính trọng",
    "厌倦": "chán ngán",
    "驼牛": "bò thồ",
    "待毙": "chờ chết",
    "贫穷": "nghèo khổ",
    "买卖": "mua bán",
    "阻隔": "ngăn cách",
    "狭窄": "chật hẹp",
    "乌龟": "rùa",
    "宅邸": "dinh thự",
    "齿轮": "bánh răng",
    "陷阱": "cạm bẫy",
    "广播": "phát sóng",
    "劳役": "lao dịch",
    "概览": "tổng quan",
    "辛坤": "Xinkun",
    "恰恰": "đúng lúc",
    "树丛": "bụi cây",
    "肆虐": "hoành hành",
    "罪魁祸首": "thủ phạm chính",
    "罪魁祸": "thủ phạm",
    "骚扰": "quấy rối",
    "沟壑纵横": "khe rãnh chằng chịt",
    "涵盖": "bao quát",
    "瓢泼泛滥": "mưa như trút gây ngập tràn",
    "阴郁": "âm u",
    "泛滥": "tràn lan",
    "树木茂盛": "cây cối rậm rạp",
    "树木茂": "cây cối rậm rạp",
    "猩猩": "khỉ đột",
    "蝙蝠": "dơi",
    "娜儿": "Na'er",
    "拦截": "chặn đánh",
    "坑洞": "hố sâu",
    "丰富": "phong phú",
    "乡渔": "dân chài quê",
    "灼烧": "bỏng rát",
    "渣浑": "cặn đục",
    "崎岖": "gồ ghề",
    "蜿蜒": "ngoằn ngoèo",
    "爆炸坑": "hố nổ",
    "馋涎": "thèm nhỏ dãi",
    "珍珠": "ngọc trai",
    "奢华": "xa hoa",
    "富丽": "lộng lẫy",
    "街巷": "ngõ phố",
    "姊妹": "chị em",
    "昼夜": "ngày đêm",
    "享乐": "hưởng lạc",
    "诡谲": "quỷ quyệt",
    "怀希": "Huaihi",
    "僧侣": "tăng lữ",
    "搁浅": "mắc cạn",
    "驯养": "thuần dưỡng",
    "油井": "giếng dầu",
    "钻井": "giếng khoan",
    "科隆": "Kelong",
    "兴盛": "hưng thịnh",
    "蜃楼": "ảo ảnh",
    "旗帜": "cờ xí",
    "茨鲁吉": "Tsrugi",
    "精锐": "tinh nhuệ",
    "云寨": "Vân Trại",
    "乌鸦窝": "Tổ Quạ",
    "休憩": "nghỉ ngơi",
    "寥寥": "ít ỏi",
    "拖拽": "kéo lê",
    "坍塌": "sụp đổ",
    "囤积": "tích trữ",
    "莫兰丁": "Molandin",
    "匆忙撤": "vội rút lui",
    "史诗": "sử thi",
    "赐予": "ban cho",
    "扭曲": "méo mó",
    "肋侧": "mạn sườn",
    "撕扯": "xé toạc",
    "挥舞": "vung vẩy",
    "驳印": "dấu loang lổ",
    "痉挛": "co giật",
    "招架": "đỡ đòn",
    "脊椎": "cột sống",
    "温床": "ổ nuôi dưỡng",
    "虚假": "giả tạo",
    "烙印": "dấu ấn",
    "烈焰": "lửa dữ",
    "鬼魅": "quỷ mị",
    "纠缠": "quấn lấy",
    "微电": "tia điện nhỏ",
    "脸颊": "gò má",
    "逆抓": "móc ngược",
    "狰狞": "hung tợn",
    "抱缠": "ôm siết",
    "捉摸": "nắm bắt",
    "匍匐": "bò sát",
    "畏惧": "khiếp sợ",
    "兄弟": "anh em",
    "超凡": "siêu phàm",
    "嫉妒": "ghen tị",
    "美丽": "xinh đẹp",
    "惊颤": "run lên vì kinh hãi",
    "怠惰": "lười biếng",
    "勤恳": "chăm chỉ",
    "牵挂": "bận lòng",
    "洞察": "nhìn thấu",
    "誓约": "lời thề",
    "约束": "ràng buộc",
    "滚烫": "nóng bỏng",
    "遵循": "tuân theo",
    "典籍": "điển tịch",
    "宛若": "tựa như",
    "席卷": "quét qua",
    "百炼": "trăm lần tôi luyện",
    "懦夫": "kẻ hèn nhát",
    "怒吼": "gầm thét",
    "惨烈": "thảm liệt",
    "沉醉": "say đắm",
    "耻辱": "nhục nhã",
    "退缩": "lùi bước",
    "亵渎": "báng bổ",
    "蛮横": "ngang ngược",
    "硬碰硬": "đối đầu trực diện",
    "万钧": "vạn cân",
    "俘虏": "tù binh",
    "推演": "diễn tập suy luận",
    "推销": "chào hàng",
    "锻炼": "rèn luyện",
    "疲惫": "mệt mỏi",
    "吹嘘": "khoác lác",
    "挑逗": "trêu chọc",
    "即便": "dù cho",
    "尴尬": "khó xử",
    "狼狈": "nhếch nhác",
    "狠狠": "mạnh tay",
    "裁剪": "cắt may",
    "仪器": "thiết bị",
    "贱卖": "bán rẻ",
    "倾诉": "giãi bày",
    "凶悍": "hung hãn",
    "震慑": "uy hiếp",
    "噪音": "tiếng ồn",
    "木桩": "cọc gỗ",
    "演讲": "diễn thuyết",
    "抛媚": "liếc mắt đưa tình",
    "嗡嗡": "vo ve",
    "博弈": "đấu trí",
    "摩擦": "cọ xát",
    "捣鼓": "mày mò",
    "渐渐": "dần dần",
    "捕捉": "bắt lấy",
    "观察": "quan sát",
    "咬牙": "nghiến răng",
    "魔鬼": "ác quỷ",
    "寂沉沉": "im lìm",
    "精髓": "tinh túy",
    "羁绊": "ràng buộc",
    "慰藉": "an ủi",
    "睡袋": "túi ngủ",
    "讲述": "kể lại",
    "探讨": "thảo luận",
    "旁敲": "đánh tiếng vòng vo",
    "筹码赌": "cược bằng chip",
    "夕阳": "hoàng hôn",
    "慌忙拦": "vội vã ngăn lại",
    "甩卖": "bán tống",
    "哄抬": "đẩy giá",
    "狠狠敲": "chặt chém mạnh tay",
    "竹杠": "chặt chém",
    "敲竹杠": "chặt chém",
    "抚慰": "xoa dịu",
    "宣泄": "trút ra",
    "填补": "lấp đầy",
    "投掷": "ném",
    "挨揍": "bị đánh",
    "软硬兼施": "vừa mềm vừa cứng",
    "弄坏": "làm hỏng",
    "轮廓": "đường nét",
    "箭射": "bắn tên",
    "箭瞄": "nhắm bắn tên",
    "呕吐": "nôn mửa",
    "吵闹": "ồn ào",
    "油灯": "đèn dầu",
    "讲荤": "kể chuyện tục",
    "熟睡": "ngủ say",
    "呼噜": "ngáy",
    "洗澡": "tắm",
    "娱乐": "giải trí",
    "精炼": "tinh luyện",
    "永恒": "vĩnh hằng",
    "阵列": "dãy bố trí",
    "肩膀": "bờ vai",
    "蒸汽": "hơi nước",
    "炼钢": "luyện thép",
    "灌溉": "tưới tiêu",
    "匠铺": "xưởng thợ",
    "忘返": "quên lối về",
    "遭遇": "đụng độ",
    "叉钉": "nỏ đinh",
    "叉炮": "nỏ pháo",
    "挖掘": "đào bới",
    "采掘": "khai thác",
    "蒸馏器": "máy chưng cất",
    "蒸馏": "chưng cất",
    "酵罐": "bồn lên men",
    "盆栽": "chậu cây",
    "温室": "nhà kính",
    "矩阵": "ma trận",
    "吞吐": "thông lượng",
    "粉末": "bột",
    "纺织": "dệt",
    "拼组": "lắp ghép",
    "微仪器": "vi thiết bị",
    "昂贵": "đắt đỏ",
    "宽敞": "rộng rãi",
    "蜗牛": "ốc sên",
    "宏伟": "hùng vĩ",
    "挥霍": "phung phí",
    "穷鬼": "kẻ nghèo",
    "货铺": "cửa hàng",
    "铺盖": "chăn chiếu",
    "床铺": "giường",
    "租给": "cho thuê",
    "床垫": "đệm",
    "绑缚柱": "cột trói",
    "羁押室": "phòng giam",
    "钢柱": "cột thép",
    "帐篷": "lều",
    "霓虹": "neon",
    "庭院": "sân vườn",
    "富贵": "phú quý",
    "阀贵胄": "môn phiệt quý tộc",
    "号施": "ra lệnh",
    "宁静": "yên tĩnh",
    "呼啸": "rít gào",
    "滚草": "cỏ lăn",
    "借宿": "ngủ nhờ",
    "徘徊": "lảng vảng",
    "嘲弄": "chế nhạo",
    "归零": "đưa về không",
    "悲惨": "bi thảm",
    "溅射": "bắn tóe",
    "累积": "tích lũy",
    "抱歉": "xin lỗi",
    "酣畅淋漓": "cực kỳ sảng khoái",
    "逼退": "ép lùi",
    "抱憾": "ôm tiếc nuối",
    "待宰羔羊": "cừu non chờ bị giết",
    "排序": "sắp xếp",
    "序号": "số thứ tự",
    "若掷骰": "nếu tung xúc xắc",
    "掷骰": "tung xúc xắc",
    "箭矢": "mũi tên",
    "均额": "mức đều nhau",
    "超额": "vượt mức",
    "剪贴": "cắt dán",
    "钥匙": "chìa khóa",
    "名垂千古": "lưu danh thiên cổ",
    "垂千古": "lưu danh thiên cổ",
    "垂千": "lưu danh",
    "宣誓": "tuyên thệ",
    "牙酸": "ê răng",
    "坠落": "rơi xuống",
    "艘坠": "con tàu rơi",
    "浓烟": "khói dày",
    "善举": "việc thiện",
    "驾驶舱": "buồng lái",
    "扫描仪": "máy quét",
    "缥缈": "mờ ảo",
    "罪孽": "tội nghiệt",
    "浓烈": "nồng nặc",
    "凭借": "dựa vào",
    "魅魔": "mị ma",
    "毛茸茸": "xù lông",
    "渗透": "thâm nhập",
    "赞美": "ca ngợi",
    "淬炼": "tôi luyện",
    "阻碍": "cản trở",
    "钱袋": "túi tiền",
    "淫纹": "dấu văn dâm dục",
    "兴奋": "phấn khích",
    "耍帅": "làm màu",
    "兴趣": "hứng thú",
    "勃勃": "sôi nổi",
    "组织": "tổ chức",
    "污渍": "vết bẩn",
    "脊梁": "xương sống",
    "屈辱": "nhục nhã",
    "喉咙": "cổ họng",
    "草草缠": "quấn tạm vội",
    "便透": "liền xuyên qua",
    "辅助": "phụ trợ",
    "协议": "giao thức",
    "赎罪": "chuộc tội",
    "艾萨": "Aisa",
    "招募": "tuyển mộ",
    "七雄": "Thất Hùng",
    "楚汉": "Sở Hán",
    "百科": "bách khoa",
    "瘟疫": "ôn dịch",
    "爆炸": "vụ nổ",
    "青铜": "đồng xanh",
    "八股": "khuôn sáo",
    "扯响": "kéo vang",
    "怒潮": "triều giận",
    "仆唾": "nô bộc",
    "携祖": "mang theo vật tổ truyền",
    "巧矮": "nhỏ nhắn lanh lợi",
    "步伐沉稳": "bước chân trầm ổn",
    "伐沉": "bước chân trầm",
    "凶狠": "hung ác",
    "丑陋": "xấu xí",
    "早早": "từ sớm",
    "呜哇呜哇哇": "Uwa uwa waa",
    "颅挂": "treo sọ",
    "阴沉": "u ám",
    "孕育": "thai nghén",
    "毗邻": "liền kề",
    "辽阔滨": "bờ biển rộng lớn",
    "草蔓延": "cỏ mọc lan",
    "沉眠": "ngủ say",
    "浑浊": "đục ngầu",
    "铜臭": "mùi tiền",
    "峻峭": "dốc đứng",
    "肃穆": "trang nghiêm",
    "奔跑": "chạy",
    "洗刷": "rửa sạch",
    "刺椎": "gai cột sống",
    "膛撕": "xé lồng ngực",
    "阵毛": "lớp lông dựng lên",
    "怀痴": "ôm lấy mê muội",
    "纯洁": "tinh khiết",
    "凌厉": "sắc bén",
    "沉浸": "đắm chìm",
    "诱惑": "cám dỗ",
    "谦卑": "khiêm nhường",
    "叉划": "vạch chéo",
    "魄熔": "hồn phách tan chảy",
    "畏迎": "sợ hãi mà đón nhận",
    "膛迎": "lồng ngực đón lấy",
    "澜舞": "sóng cuộn múa",
    "震彻": "chấn động xuyên thấu",
    "昂扬": "hăng hái",
    "狡诈": "gian xảo",
    "掩盖谎": "che lời nói dối",
    "怀抱": "ôm ấp",
    "蛊惑": "mê hoặc",
    "熟悉": "quen thuộc",
    "佯退": "giả vờ lui",
    "欺骗": "lừa dối",
    "诱骗": "dụ dỗ",
    "乘胜": "thừa thắng",
    "阴狠": "âm hiểm độc ác",
    "软肋": "điểm yếu",
    "顾虑": "băn khoăn",
    "刁钻": "xảo quyệt",
    "悄悄": "lặng lẽ",
    "胜负": "thắng bại",
    "魅影": "bóng mị ảnh",
    "恍惚": "mơ hồ",
    "虚虚": "hư ảo",
    "狠辣": "tàn nhẫn",
    "影隙": "khe bóng",
    "夜瞳": "đồng tử đêm",
    "逐微": "theo từng chút",
    "匠艺": "tay nghề nghệ nhân",
    "缚鸡": "trói gà",
    "疲倦": "mệt mỏi",
    "考验": "thử thách",
    "硬扛": "gồng chịu",
    "斜架": "chống chéo",
    "稍微": "hơi chút",
    "倾斜": "nghiêng",
    "硬撞": "va mạnh",
    "微晃": "rung nhẹ",
    "巧劲": "lực khéo",
    "洞悉": "thấu hiểu",
    "微妙": "tinh tế",
    "瞬即": "tức khắc",
    "蛛母芯": "lõi nhện mẹ",
    "微缩": "thu nhỏ",
    "呆冥": "ngẩn ngơ",
    "胆识": "gan dạ",
    "吹草": "thổi cỏ",
    "丝微": "mảy may",
    "额迅": "nhanh trên trán",
    "哪瞟": "liếc đâu đó",
    "拿匕": "cầm dao găm",
    "猛扎": "đâm mạnh",
    "俄罗": "Oro",
    "辱骂": "chửi rủa",
    "喘吁吁": "thở hổn hển",
    "肩肘": "vai và khuỷu",
    "挥砍": "vung chém",
    "咔哒": "cạch",
    "拨便": "gạt là xuyên",
    "盗电": "trộm điện",
    "阻针": "kim cản",
    "精美": "tinh xảo",
    "百米": "trăm mét",
    "奏印": "dấu vết dồn dập",
    "惹怒": "chọc giận",
    "惊叹": "kinh ngạc",
    "劳累": "mệt nhọc",
    "浸透": "thấm đẫm",
    "躁抓": "bồn chồn cào cấu",
    "喧哗": "ồn ào",
    "刺激": "kích thích",
    "助眠": "giúp ngủ",
    "胃酸": "axit dạ dày",
    "胆汁": "mật",
    "透彻": "thấu triệt",
    "推敲": "cân nhắc",
    "弄懂": "hiểu ra",
    "醍醐灌": "như được khai sáng",
    "飙升": "tăng vọt",
    "践弄": "giày xéo",
    "惊艳": "choáng ngợp",
    "胡扯": "nói nhảm",
    "雄辩": "hùng biện",
    "凄惨": "thê thảm",
    "演绎": "diễn giải",
    "摇摇": "lắc lư",
    "巧舌": "khéo miệng",
    "挑拨": "kích động",
    "暧昧": "mập mờ tình tứ",
    "瞎蒙": "đoán mò",
    "跌跌撞撞": "loạng choạng",
    "夜魔": "dạ ma",
    "咔咔": "răng rắc",
    "夸张": "phóng đại",
    "挥洒": "vung vãi",
    "惊呼": "kêu lên kinh ngạc",
    "跳跃": "nhảy vọt",
    "登峰": "lên tới đỉnh",
    "肠胃": "dạ dày ruột",
    "烦躁": "bực bội",
    "插翅": "mọc cánh",
    "窟乐": "ổ vui chơi",
    "润丰": "màu mỡ phì nhiêu",
    "百花楼": "Lầu Bách Hoa",
    "乐百花楼": "Lầu Bách Hoa vui thú",
    "账识": "hiểu sổ sách",
    "待顺": "chờ thuần phục",
    "盗窃": "trộm cắp",
    "漏洞": "lỗ hổng",
    "富饶": "trù phú",
    "惨爪": "móng vuốt thảm khốc",
    "蔓延": "lan rộng",
    "崇尚": "sùng thượng",
    "伊洛": "Yiluo",
    "抓捕": "bắt giữ",
    "撤销": "hủy bỏ",
    "浏览": "duyệt xem",
    "执照": "giấy phép",
    "卧床": "nằm liệt giường",
    "履历": "lý lịch",
    "赤铜": "đồng đỏ",
    "华丽": "lộng lẫy",
    "牙签": "tăm",
    "僧袍": "áo tăng",
    "丝绸": "lụa",
    "浅棕": "nâu nhạt",
    "瘦狼": "sói gầy",
    "秃鹫": "kền kền",
    "稻米": "gạo",
    "渔获": "sản lượng cá",
    "珊瑚": "san hô",
    "希诺": "Hino",
    "玫瑰": "hoa hồng",
    "关键词": "từ khóa",
    "键词": "từ khóa",
    "街谈巷议": "lời đồn đầu đường cuối ngõ",
    "铅笔": "bút chì",
    "悲啊": "thật bi thảm",
    "例均": "bình quân theo ví dụ",
    "奥克兰": "Okran",
    "奥克兰赐福": "phúc lành của Okran",
    "Okran赐福": "Okran ban phúc",
    "菲尼克斯": "Phoenix",
    "菲尼克斯六十二世": "Phoenix đời thứ sáu mươi hai",
    "联合帝国": "Đế chế Liên Hợp",
    "联合城": "Thành Liên Hợp",
    "联合": "Liên Hợp",
    "赫夫特城": "thành Heft",
    "赫夫特": "Heft",
    "赫夫": "Heft",
    "神圣教国": "Thánh Quốc",
    "圣国": "Thánh Quốc",
    "圣骑士": "thánh kỵ sĩ",
    "圣火": "Thánh Hỏa",
    "圣杖": "thánh trượng",
    "圣主": "Thánh Chủ",
    "圣国牧师": "mục sư Thánh Quốc",
    "圣国信徒": "tín đồ Thánh Quốc",
    "神谕": "thần dụ",
    "祭司": "tế tư",
    "异端": "dị đoan",
    "异教徒": "dị giáo đồ",
    "沙克王国": "Vương quốc Shak",
    "沙克人": "người Shak",
    "沙克族": "tộc Shak",
    "沙克": "Shak",
    "克拉尔": "Kral",
    "克拉尔之选": "Người được Kral chọn",
    "巴斯特": "Bast",
    "铁之径王城": "Vương thành Lối Sắt",
    "铁之径": "Lối Sắt",
    "远古血盟": "Huyết Minh Cổ Đại",
    "反蓄奴者": "quân chống nô lệ",
    "蓄奴": "nuôi giữ nô lệ",
    "奴隶商人": "thương nhân nô lệ",
    "商人行会": "Hiệp hội Thương nhân",
    "食人族部落": "bộ lạc ăn thịt người",
    "食人族": "tộc ăn thịt người",
    "猎犬帮": "bang Chó Săn",
    "第二帝国": "Đế Quốc Thứ Hai",
    "黑暗之地": "vùng đất hắc ám",
    "娜尔可": "Narko",
    "娜尔": "Nar",
    "库尔林": "Kurlin",
    "鱼形人": "người cá",
    "渔岛": "đảo Cá",
    "螃蟹教团": "giáo đoàn Cua",
    "螃蟹女王": "Nữ hoàng Cua",
    "螃蟹镇": "thị trấn Cua",
    "螃蟹": "cua",
    "蟹型铠甲": "giáp dạng cua",
    "蟹壳护甲": "giáp mai cua",
    "斯威士": "Swais",
    "斯威士国": "nước Swais",
    "斯威士之剑": "Kiếm Swais",
    "洼地泻湖镇": "thị trấn đầm phá vùng trũng",
    "水泡山丘": "đồi Bong Bóng",
    "重生镇": "Trấn Tái Sinh",
    "重生": "Tái Sinh",
    "人生谷底": "Đáy đời",
    "黑暗之女": "Con gái bóng tối",
    "贵族之子": "Con trai quý tộc",
    "大剑": "Đại kiếm",
    "男奴": "Nam nô",
    "流浪者": "Kẻ lang thang",
    "未知梦想": "Giấc mơ chưa biết",
    "异端之火": "Ngọn lửa dị đoan",
    "奴隶主": "Chủ nô",
    "怪物猎人": "Thợ săn quái vật",
    "顶级猎手": "Thợ săn đỉnh cao",
    "神圣十字军东征": "Thập tự chinh Thánh Quốc",
    "流浪商人": "Thương nhân lang thang",
    "带着狗的家伙": "Gã đi cùng chó",
    "螃蟹狂热者": "Kẻ cuồng tín Cua",
    "铁剑": "kiếm sắt",
    "生锈": "rỉ sét",
    "破旧": "cũ nát",
    "皮甲": "giáp da",
    "干肉": "thịt khô",
    "贵族服饰": "trang phục quý tộc",
    "短刀": "dao ngắn",
    "私人奴隶": "nô lệ riêng",
    "消瘦": "gầy gò",
    "骨瘦如柴": "gầy trơ xương",
    "神情麻木": "vẻ mặt đờ đẫn",
    "长期营养不良": "suy dinh dưỡng lâu dài",
    "眼神空洞": "ánh mắt rỗng không",
    "行动谨慎": "hành động thận trọng",
    "机械": "máy móc",
    "饥肠辘辘": "đói cồn cào",
    "肠辘辘": "bụng đói réo",
    "失去左手": "mất tay trái",
    "通缉令": "lệnh truy nã",
    "传说": "truyền thuyết",
    "自由土地": "vùng đất tự do",
    "叛乱分子": "kẻ nổi loạn",
    "后裔": "hậu duệ",
    "合法首领": "thủ lĩnh hợp pháp",
    "女皇": "nữ hoàng",
    "宝座": "ngai báu",
    "坐以待毙": "ngồi chờ chết",
    "毁灭的入侵": "cuộc xâm lăng hủy diệt",
    "强有力": "mạnh mẽ",
    "复兴": "phục hưng",
    "难民": "dân tị nạn",
    "抛在脑后": "bỏ lại sau lưng",
    "野兽": "dã thú",
    "繁荣": "phồn vinh",
    "荒凉": "hoang vắng",
    "破败": "đổ nát",
    "贫瘠": "cằn cỗi",
    "无家可归": "vô gia cư",
    "被遗弃": "bị bỏ rơi",
    "小狗": "chó con",
    "行刑队": "đội hành quyết",
    "武士巡逻队": "đội tuần tra võ sĩ",
    "大沙漠": "Đại Sa Mạc",
    "土匪": "thổ phỉ",
    "奴隶营": "trại nô lệ",
    "野狗": "chó hoang",
    "极恶之地": "vùng đất cực ác",
    "东海岸": "bờ đông",
    "盐风": "gió mặn",
    "蟹腥味": "mùi tanh của cua",
    "血誓": "huyết thệ",
    "试炼": "thử luyện",
    "新兵": "tân binh",
    "无坚不摧": "không gì phá nổi",
    "唯一真理": "chân lý duy nhất",
    "桀骜": "ngang tàng",
    "蘑菇": "nấm",
    "蟑螂": "gián",
    "熙攘": "nhộn nhịp",
    "羡慕": "ngưỡng mộ",
    "妖冶": "diễm lệ",
    "烟瘴": "sương độc",
    "宇宙": "vũ trụ",
    "喀琉": "Caliu",
    "蓬勃": "phồn thịnh",
    "弘扬": "phát huy",
    "薪柴": "củi",
    "亢奋": "hưng phấn",
}

COMMON = {
    "小队成员": "Thành viên đội",
    "我方派系名称": "Tên phe phái của ta",
    "所处位置": "Vị trí đang ở",
    "当前事件": "Sự kiện hiện tại",
    "世界": "Thế giới",
    "天数": "Số ngày",
    "时间": "Thời gian",
    "上午": "Buổi sáng",
    "区域": "Khu vực",
    "城镇": "Thị trấn",
    "成员": "Thành viên",
    "视野": "Tầm nhìn",
    "异地": "Nơi khác",
    "据点": "Cứ điểm",
    "局势": "Cục diện",
    "任务系统": "Hệ thống nhiệm vụ",
    "往事": "Chuyện cũ",
    "闲言": "Lời đồn",
    "金钱": "Tiền",
    "名字": "Tên",
    "姓名": "Họ tên",
    "名称": "Tên gọi",
    "性别": "Giới tính",
    "男性": "Nam",
    "女性": "Nữ",
    "年龄": "Tuổi",
    "身份": "Thân phận",
    "外貌描述": "Mô tả ngoại hình",
    "外貌": "Ngoại hình",
    "体型": "Dáng vóc",
    "身高": "Chiều cao",
    "状态": "Trạng thái",
    "立场": "Lập trường",
    "派系": "Phe phái",
    "等级": "Cấp độ",
    "经验值": "Điểm kinh nghiệm",
    "当前": "Hiện tại",
    "升级所需": "Cần để lên cấp",
    "属性点": "Điểm thuộc tính",
    "特质点": "Điểm đặc tính",
    "攻击次数": "Số lần tấn công",
    "心理想法": "Suy nghĩ trong đầu",
    "人际关系": "Quan hệ nhân vật",
    "主武器": "Vũ khí chính",
    "副武器": "Vũ khí phụ",
    "护甲": "Giáp",
    "血量": "Máu",
    "最大": "Tối đa",
    "种族": "Chủng tộc",
    "属性": "Thuộc tính",
    "特质": "Đặc tính",
    "临时特质": "Đặc tính tạm thời",
    "创伤": "Chấn thương",
    "背包": "Ba lô",
    "负重": "Tải trọng",
    "物品": "Vật phẩm",
    "分类": "Phân loại",
    "子分类": "Phân loại phụ",
    "数量": "Số lượng",
    "重量": "Khối lượng",
    "价值": "Giá trị",
    "介绍": "Mô tả",
    "描述": "Mô tả",
    "种类": "Loại",
    "品质": "Phẩm chất",
    "伤害骰": "Xúc xắc sát thương",
    "伤害类型": "Loại sát thương",
    "防护能力": "Năng lực phòng hộ",
    "关系": "Quan hệ",
    "看法": "Nhìn nhận",
    "好感度": "Độ thiện cảm",
    "友方派系": "Phe thân thiện",
    "敌对派系": "Phe thù địch",
    "已知派系": "Phe đã biết",
    "结盟原因": "Lý do liên minh",
    "敌对原因": "Lý do thù địch",
    "主任务状态": "Trạng thái nhiệm vụ chính",
    "子任务": "Nhiệm vụ phụ",
    "进度": "Tiến độ",
    "目标": "Mục tiêu",
    "已完成": "Đã hoàn thành",
    "进行中": "Đang tiến hành",
    "交友记录": "Ghi chép kết giao",
    "城镇记录": "Ghi chép thị trấn",
    "城镇纪略": "Lược ký thị trấn",
    "死亡名单": "Danh sách tử vong",
    "关键记忆": "Ký ức then chốt",
    "日期": "Ngày",
    "死亡": "Đã chết",
    "存活": "Còn sống",
    "未知区域": "Khu vực chưa biết",
    "未知城镇": "Thị trấn chưa biết",
    "未知": "Không rõ",
    "无派系": "Không phe phái",
    "无": "Không",
    "陌生人": "Người lạ",
    "友方": "Phe ta",
    "中立": "Trung lập",
    "敌方": "Phe địch",
    "力量": "Sức mạnh",
    "敏捷": "Nhanh nhẹn",
    "感知": "Cảm nhận",
    "体质": "Thể chất",
    "韧性": "Ý chí",
    "智力": "Trí tuệ",
    "魅力": "Sức hút",
    "全属性": "Toàn thuộc tính",
    "基础": "Cơ bản",
    "手动加成": "Cộng tay",
    "加成": "Cộng thêm",
    "潜行": "Ẩn nấp",
    "运动": "Vận động",
    "偷窃": "Trộm cắp",
    "撬锁": "Phá khóa",
    "暗杀": "Ám sát",
    "侦查": "Trinh sát",
    "科学": "Khoa học",
    "工程学": "Kỹ thuật",
    "战地急救": "Cấp cứu chiến trường",
    "机器人学": "Cơ khí người máy",
    "交易": "Giao dịch",
    "说服": "Thuyết phục",
    "烹饪": "Nấu nướng",
    "重甲": "Giáp nặng",
    "中甲": "Giáp trung",
    "轻甲": "Giáp nhẹ",
    "无甲": "Không giáp",
    "武器": "Vũ khí",
    "装备": "Trang bị",
    "食物": "Thức ăn",
    "饮品": "Đồ uống",
    "医疗用品": "Vật phẩm y tế",
    "科研道具": "Đạo cụ nghiên cứu",
    "任务道具": "Đạo cụ nhiệm vụ",
    "矿石": "Quặng",
    "布料": "Vải",
    "金属材料": "Vật liệu kim loại",
    "农作物": "Nông sản",
    "其他": "Khác",
    "取消": "Hủy",
    "关闭": "Đóng",
    "保存中": "Đang lưu...",
    "保存失败，请查看控制台": "Lưu thất bại, hãy xem console",
    "保存": "Lưu",
    "导入": "Nhập",
    "导入失败：文件格式不正确": "Nhập thất bại: định dạng file không đúng",
    "下一步": "Bước tiếp",
    "完成": "Hoàn tất",
    "游玩须知": "Lưu ý khi chơi",
    "已分配": "Đã phân bổ ",
    "剩余": "Còn lại ",
    "队员": "Đội viên ",
    "未选择": "Chưa chọn",
    "眼睛": "Mắt",
    "发色": "Màu tóc",
    "性格": "Tính cách",
    "发型": "Kiểu tóc",
    "属性类": "Nhóm thuộc tính",
    "重抽属性类": "Rút lại nhóm thuộc tính",
    "生活类": "Nhóm đời sống",
    "重抽生活类": "Rút lại nhóm đời sống",
    "整活类": "Nhóm trò vui",
    "重抽整活类": "Rút lại nhóm trò vui",
    "自定义特质（仅 1 个）": "Đặc tính tự định nghĩa (chỉ 1)",
    "特质名称": "Tên đặc tính",
    "特质描述": "Mô tả đặc tính",
    "自定义种族": "Chủng tộc tự định nghĩa",
    "出生区域": "Khu vực xuất thân",
    "自带主线": "Có sẵn tuyến chính",
    "大失败": "Đại thất bại",
    "大成功": "Đại thành công",
    "失败": "Thất bại",
    "成功": "Thành công",
    "略处下风": "Hơi rơi vào hạ phong",
    "悲惨失败": "Thất bại thảm khốc",
    "血战惜败": "Huyết chiến thua tiếc",
    "略处上风": "Hơi chiếm thượng phong",
    "血战险胜": "Huyết chiến thắng hiểm",
    "酣畅大胜": "Đại thắng sảng khoái",
    "史诗大捷": "Đại thắng sử thi",
    "势均力敌": "Ngang tài ngang sức",
    "投降": "Đầu hàng",
    "被制服": "Bị khống chế",
    "已被制服": "Đã bị khống chế",
    "制服成功": "Khống chế thành công",
    "已逃跑": "Đã bỏ chạy",
    "逃跑失败": "Bỏ chạy thất bại",
    "撤退失败，无法移动。": "Rút lui thất bại, không thể di chuyển.",
    "无法移动": "Không thể di chuyển",
    "继续战斗": "Tiếp tục chiến đấu",
    "休克": "Sốc",
    "昏迷": "Hôn mê",
    "眩晕": "Choáng",
    "骨折": "Gãy xương",
    "出血层数": "Tầng chảy máu",
    "流血层数": "Tầng chảy máu",
    "武术": "Võ thuật",
    "武术类": "Loại võ thuật",
    "军刀类": "Loại quân đao",
    "武士刀": "Katana",
    "砍刀": "Đao chặt",
    "钝器类": "Loại vũ khí cùn",
    "盾牌": "Khiên",
    "医疗失败": "Chữa trị thất bại",
    "未选择医疗物品": "Chưa chọn vật phẩm y tế",
    "此角色背包没有可用医疗物品": "Ba lô nhân vật này không có vật phẩm y tế khả dụng",
    "训练终端": "Trạm huấn luyện",
    "休息交谈": "Nghỉ ngơi trò chuyện",
    "基础药品": "Thuốc cơ bản",
    "高级药品": "Thuốc cao cấp",
    "高级武器": "Vũ khí cao cấp",
    "高级护甲": "Giáp cao cấp",
    "奴隶处理": "Xử lý nô lệ",
    "奴隶": "Nô lệ",
    "你": "Bạn",
    "心情值": "Điểm tâm trạng",
    "心情沉重": "Tâm trạng nặng nề",
    "普通": "Bình thường",
    "退出全屏模式": "Thoát toàn màn hình",
    "进入全屏模式": "Vào toàn màn hình",
    "重命名据点": "Đổi tên cứ điểm",
    "入侵": "Xâm nhập",
    "骨人": "Người Xương",
}


EXTRA = {
    # Trạng thái / giao diện chung
    "暂无": "hiện chưa có",
    "未初始化": "chưa khởi tạo",
    "初始化": "khởi tạo",
    "记录": "ghi chép",
    "删除": "xóa",
    "重命名": "đổi tên",
    "确认": "xác nhận",
    "取消": "hủy",
    "返回": "trở về",
    "进入": "đi vào",
    "离队": "rời đội",
    "进队": "vào đội",
    "入队": "gia nhập đội",
    "去向": "hướng đi",
    "移至": "chuyển đến",
    "移入": "chuyển vào",
    "移出": "đưa ra khỏi",
    "移除": "loại bỏ",
    "提交调整": "gửi điều chỉnh",
    "调整": "điều chỉnh",
    "编辑模式": "chế độ chỉnh sửa",
    "删除小队": "xóa đội",
    "确认删除": "xác nhận xóa",
    "确认移除": "xác nhận loại bỏ",
    "确认移至": "xác nhận chuyển đến",
    "确认移出": "xác nhận đưa ra khỏi",
    "显示": "hiển thị",
    "隐藏": "ẩn",
    "折叠": "thu gọn",
    "展开": "mở rộng",
    "重抽": "rút lại",
    "重置": "đặt lại",
    "上架": "đưa lên",
    "下架": "hạ xuống",
    "新建": "xây mới",
    "未选择": "chưa chọn",
    "知道了": "đã rõ",
    "广交良友": "kết thêm bạn tốt",
    "请选择": "vui lòng chọn",
    "请输入": "vui lòng nhập",
    "需要": "cần",
    "无法删除": "không thể xóa",
    "无法移动": "không thể di chuyển",
    "无法使用": "không thể dùng",
    "如果": "nếu",
    "是否": "có hay không",
    "该": "này",
    "这个": "này",
    "这里": "nơi này",
    "现在": "hiện tại",
    "当前": "hiện tại",
    "内容": "nội dung",
    "简介": "mô tả",
    "内容现状": "nội dung hiện tại",
    "日志": "nhật ký",
    "任务日志": "nhật ký nhiệm vụ",
    "任务": "nhiệm vụ",
    "主任务": "nhiệm vụ chính",
    "子任务": "nhiệm vụ phụ",
    "奖励": "phần thưởng",
    "损失": "tổn thất",
    "结果": "kết quả",
    "效果": "hiệu quả",
    "规则": "quy tắc",
    "规则详解": "giải thích quy tắc",
    "详解": "giải thích",
    "逻辑": "logic",
    "条件": "điều kiện",
    "要求": "yêu cầu",
    "说明": "thuyết minh",
    "说明文字": "thuyết minh",
    "提示": "gợi ý",
    "提示文字": "gợi ý",
    "惩罚": "hình phạt",
    "提升": "tăng cường",
    "训练": "huấn luyện",
    "管理": "quản lý",
    "模板": "mẫu",
    "背景故事": "bối cảnh câu chuyện",
    "世界观": "thế giới quan",
    "设定": "thiết lập",
    "详细设定": "thiết lập chi tiết",
    "角色模板": "mẫu nhân vật",
    "自定义": "tự định nghĩa",
    "加载": "tải",
    "保存": "lưu",
    "导入": "nhập",
    "导出": "xuất",
    "打开": "mở",
    "关闭": "đóng",
    "选项": "tùy chọn",
    "界面": "giao diện",
    "界面设置": "thiết lập giao diện",
    "属性分配": "phân bổ thuộc tính",
    "人物模板": "mẫu nhân vật",
    "队伍模板": "mẫu đội",
    "背景": "bối cảnh",
    "故事": "câu chuyện",
    "故事描写": "miêu tả câu chuyện",
    "保存背景故事": "lưu bối cảnh câu chuyện",
    "保存详细设定": "lưu thiết lập chi tiết",
    "选择": "chọn",
    "确认": "xác nhận",
    "取消": "hủy",
    "默认": "mặc định",
    "开始": "bắt đầu",
    "结束": "kết thúc",
    "继续": "tiếp tục",
    "创建": "tạo",
    "编辑": "chỉnh sửa",
    "删除": "xóa",
    "重命名": "đổi tên",
    "读取": "đọc",
    "写入": "ghi",
    "导入失败": "nhập thất bại",
    "保存失败": "lưu thất bại",
    "配置": "cấu hình",
    "设置信息": "thông tin cài đặt",
    "按钮": "nút",
    "页面": "trang",
    "显示": "hiển thị",
    "隐藏": "ẩn",
    "标题": "tiêu đề",
    "说明": "thuyết minh",
    "提示": "gợi ý",
    "简介": "giới thiệu",
    "内容": "nội dung",
    "昆": "côn",
    "虫": "trùng",
    "蟲": "trùng",
    "生": "sinh",
    "理": "lý",
    "结": "kết",
    "構": "cấu",
    "构": "cấu",
    "显": "hiển",
    "顯": "hiển",
    "著": "trứ",
    "特": "đặc",
    "征": "trưng",
    "细": "tế",
    "細": "tế",
    "长": "trường",
    "長": "trường",
    "枯": "khô",
    "枝": "chi",
    "般": "bàn",
    "四": "tứ",
    "肢": "chi",
    "脆": "giòn",
    "弱": "nhược",
    "腔": "khoang",
    "骼": "cách",
    "奇": "kỳ",
    "导": "đạo",
    "導": "đạo",
    "致": "trí",
    "承": "thừa",
    "受": "thụ",
    "痛": "thống",
    "苦": "khổ",
    "怕": "sợ",
    "黑": "hắc",
    "暗": "ám",
    "邪": "tà",
    "恶": "ác",
    "惡": "ác",
    "狂": "cuồng",
    "暴": "bạo",
    "愚": "ngu",
    "蠢": "xuẩn",
    "奴": "nô",
    "婪": "lam",
    "贪": "tham",
    "貪": "tham",
    "欲": "dục",
    "望": "vọng",
    "逃": "đào",
    "亡": "vong",
    "流": "lưu",
    "浪": "lãng",
    "者": "giả",
    "孤": "cô",
    "独": "độc",
    "獨": "độc",
    "绝": "tuyệt",
    "望": "vọng",
    "幸": "hạnh",
    "福": "phúc",
    "求": "cầu",
    "杀": "sát",
    "殺": "sát",
    "戮": "lục",
    "嗜": "thị",
    "血": "huyết",
    "修": "tu",
    "复": "phục",
    "復": "phục",
    "机": "cơ",
    "機": "cơ",
    "能": "năng",
    "力": "lực",
    "伤": "thương",
    "口": "khẩu",
    "愈": "dũ",
    "合": "hợp",
    "饥": "cơ",
    "飢": "cơ",
    "饿": "ngạ",
    "餓": "ngạ",
    "折": "chiết",
    "磨": "ma",
    "内": "nội",
    "內": "nội",
    "心": "tâm",
    "灵": "linh",
    "靈": "linh",
    "魂": "hồn",
    "冷": "lãnh",
    "暖": "noãn",
    "幻": "ảo",
    "境": "cảnh",
    "未": "vị",
    "来": "lai",
    "來": "lai",
    "预": "dự",
    "預": "dự",
    "见": "kiến",
    "見": "kiến",
    "思": "tư",
    "绪": "tự",
    "緒": "tự",
    "崩": "băng",
    "溃": "khối",
    "潰": "khối",
    "梦": "mộng",
    "夢": "mộng",
    "境": "cảnh",
    "指": "chỉ",
    "引": "dẫn",
    "一": "một",
    "们": "chúng",
    "他": "hắn",
    "她": "cô ấy",
    "着": "đang",
    "就": "liền",
    "死": "chết",
    "而": "và",
    "只": "chỉ",
    "过": "qua",
    "得": "được",
    "如": "như",
    "片": "mảnh",
    "并": "và",
    "都": "đều",
    "没": "không",
    "让": "khiến",
    "破": "phá",
    "圣": "thánh",
    "子": "tử",
    "作": "làm",
    "钝": "cùn",
    "我": "ta",
    "要": "muốn",
    "终": "cuối",
    "此": "này",
    "它": "nó",
    "去": "đi",
    "种": "giống",
    "斯": "s",
    "因": "do",
    "把": "đem",
    "色": "sắc",
    "情": "tình",
    "或": "hoặc",
    "割": "cắt",
    "比": "so",
    "残": "tàn",
    "克": "khắc",
    "代": "đời",
    "方": "phương",
    "还": "còn",
    "按": "theo",
    "且": "và",
    "明": "minh",
    "找": "tìm",
    "利": "lợi",
    "起": "khởi",
    "处": "xứ",
    "服": "phục",
    "第": "thứ",
    "金": "kim",
    "立": "lập",
    "活": "sống",
    "总": "tổng",
    "巢": "tổ",
    "何": "hà",
    "制": "chế",
    "光": "quang",
    "化": "hóa",
    "意": "ý",
    "所": "sở",
    "进": "tiến",
    "通": "thông",
    "造": "tạo",
    "任": "nhiệm",
    "断": "đoạn",
    "远": "viễn",
    "单": "đơn",
    "感": "cảm",
    "打": "đả",
    "干": "can",
    "坦": "đàn",
    "说": "thuyết",
    "解": "giải",
    "看": "khán",
    "度": "độ",
    "间": "gian",
    "衣": "y",
    "脑": "não",
    "教": "giáo",
    "相": "tương",
    "好": "hảo",
    "顶": "đỉnh",
    "信": "tín",
    "建": "kiến",
    "真": "chân",
    "使": "sử",
    "端": "đoan",
    "期": "kỳ",
    "十": "thập",
    "领": "lĩnh",
    "几": "kỷ",
    "曾": "tằng",
    "至": "chí",
    "老": "lão",
    "却": "thế nhưng",
    "追": "truy",
    "烂": "nát",
    "尔": "nhĩ",
    "寻": "tầm",
    "国": "quốc",
    "边": "biên",
    "怪": "quái",
    "夺": "đoạt",
    "别": "biệt",
    "么": "nào",
    "知": "tri",
    "许": "hứa",
    "游": "du",
    "巨": "cự",
    "狩": "săn",
    "尽": "tận",
    "蜂": "ong",
    "行": "hành",
    "动": "động",
    "铁": "thiết",
    "卡": "cát",
    "加": "gia",
    "螃": "bàng",
    "二": "nhị",
    "亲": "thân",
    "敌": "địch",
    "声": "thanh",
    "友": "hữu",
    "乎": "hồ",
    "令": "lệnh",
    "坚": "kiên",
    "拉": "lạp",
    "智": "trí",
    "才": "tài",
    "走": "tẩu",
    "言": "ngôn",
    "荣": "vinh",
    "狗": "cẩu",
    "当": "đương",
    "清": "thanh",
    "柄": "bính",
    "仇": "cừu",
    "巴": "ba",
    "吧": "ba",
    "团": "đoàn",
    "听": "thính",
    "鱼": "ngư",
    "争": "tranh",
    "群": "quần",
    "实": "thực",
    "戴": "đái",
    "程": "trình",
    "腐": "phủ",
    "底": "để",
    "安": "an",
    "话": "thoại",
    "什": "thập",
    "样": "dạng",
    "酷": "khốc",
    "准": "chuẩn",
    "先": "tiên",
    "近": "cận",
    "某": "mỗ",
    "今": "kim",
    "兽": "thú",
    "液": "dịch",
    "形": "hình",
    "剥": "bóc",
    "甚": "thậm",
    "持": "trì",
    "裂": "liệt",
    "粗": "thô",
    "套": "bộ",
    "师": "sư",
    "祭": "tế",
    "非": "phi",
    "做": "tác",
    "价": "giá",
    "直": "trực",
    "深": "thâm",
    "刻": "khắc",
    "味": "vị",
    "亚": "á",
    "叛": "phản",
    "取": "thủ",
    "吃": "thực",
    "壳": "xác",
    "龙": "long",
    "抗": "kháng",
    "碎": "toái",
    "严": "nghiêm",
    "迫": "bức",
    "武": "võ",
    "鲜": "tươi",
    "紧": "khẩn",
    "留": "lưu",
    "卫": "vệ",
    "骸": "hài",
    "聚": "tụ",
    "址": "chỉ",
    "据": "cứ",
    "周": "chu",
    "集": "tập",
    "偏": "thiên",
    "密": "mật",
    "资": "tư",
    "基": "cơ",
    "偶": "ngẫu",
    "托": "thác",
    "园": "viên",
    "犯": "phạm",
    "散": "tán",
    "较": "giảo",
    "附": "phụ",
    "靠": "khảo",
    "监": "giám",
    "猫": "miêu",
    "赏": "thưởng",
    "伯": "bá",
    "穹": "quỳnh",
    "驻": "trú",
    "戒": "giới",
    "需": "tu",
    "巡": "tuần",
    "伽": "già",
    "似": "tự",
    "稀": "hi",
    "阿": "a",
    "贸": "mậu",
    "蔽": "bế",
    "弃": "khí",
    "屋": "ốc",
    "搜": "sưu",
    "缺": "khuyết",
    "限": "hạn",
    "充": "xung",
    "袭": "tập",
    "央": "ương",
    "冒": "mạo",
    "劣": "liệt",
    "匪": "phỉ",
    "尖": "tiêm",
    "源": "nguyên",
    "德": "đức",
    "繁": "phồn",
    "谨": "cẩn",
    "慎": "thận",
    "疑": "nghi",
    "拾": "thập",
    "玩": "ngoạn",
    "抵": "để",
    "息": "tức",
    "觉": "giác",
    "覺": "giác",
    "压": "áp",
    "壓": "áp",
    "系": "hệ",
    "具": "cụ",
    "参": "tham",
    "參": "tham",
    "决": "quyết",
    "決": "quyết",
    "两": "lưỡng",
    "兩": "lưỡng",
    "麻": "ma",
    "披": "phi",
    "徒": "đồ",
    "司": "ti",
    "衬": "xứng",
    "壯": "tráng",
    "壮": "tráng",
    "忍": "nhẫn",
    "毫": "hào",
    "唯": "duy",
    "达": "đạt",
    "達": "đạt",
    "缝": "phùng",
    "縫": "phùng",
    "倒": "đảo",
    "放": "phóng",
    "各": "các",
    "称": "xưng",
    "稱": "xưng",
    "欢": "hoan",
    "歡": "hoan",
    "突": "đột",
    "肤": "phu",
    "膚": "phu",
    "离": "ly",
    "離": "ly",
    "币": "tệ",
    "幣": "tệ",
    "权": "quyền",
    "權": "quyền",
    "掠": "lược",
    "铠": "khải",
    "鎧": "khải",
    "尼": "ni",
    "女": "nữ",
    "偷": "thâu",
    "习": "tập",
    "習": "tập",
    "座": "tọa",
    "腥": "tanh",
    "伏": "phục",
    "刚": "cương",
    "剛": "cương",
    "疯": "phong",
    "瘋": "phong",
    "恩": "ân",
    "容": "dung",
    "掌": "chưởng",
    "默": "mặc",
    "戏": "hí",
    "戲": "hí",
    "证": "chứng",
    "證": "chứng",
    "语": "ngữ",
    "語": "ngữ",
    "父": "phụ",
    "官": "quan",
    "迷": "mê",
    "应": "ưng",
    "應": "ưng",
    "等": "đẳng",
    "毁": "hủy",
    "毀": "hủy",
    "太": "thái",
    "够": "câu",
    "夠": "câu",
    "悬": "huyền",
    "懸": "huyền",
    "匿": "nặc",
    "沿": "duyên",
    "痕": "ngân",
    "壁": "bích",
    "绕": "nhiễu",
    "繞": "nhiễu",
    "壤": "nhưỡng",
    "叫": "khiếu",
    "责": "trách",
    "責": "trách",
    "供": "cung",
    "哨": "tiếu",
    "毒": "độc",
    "贝": "bối",
    "貝": "bối",
    "乏": "phạp",
    "共": "cộng",
    "栖": "thê",
    "棲": "thê",
    "飞": "phi",
    "飛": "phi",
    "牢": "lao",
    "尘": "trần",
    "塵": "trần",
    "星": "tinh",
    "混": "hỗn",
    "障": "chướng",
    "洼": "oa",
    "窪": "oa",
    "运": "vận",
    "運": "vận",
    "盾": "thuẫn",
    "植": "trực",
    "埋": "mai",
    "荡": "đãng",
    "蕩": "đãng",
    "括": "quát",
    "盘": "bàn",
    "盤": "bàn",
    "径": "kính",
    "徑": "kính",
    "坐": "tọa",
    "收": "thu",
    "雷": "lôi",
    "依": "y",
    "马": "mã",
    "馬": "mã",
    "警": "cảnh",
    "索": "tỏa",
    "仿": "phảng",
    "佛": "phật",
    "汗": "hãn",
    "根": "căn",
    "占": "chiếm",
    "简": "giản",
    "簡": "giản",
    "区": "khu",
    "區": "khu",
    "匮": "quỹ",
    "匱": "quỹ",
    "留": "lưu",
    "手段": "cách thức",
    "战斗": "chiến đấu",
    "后勤": "hậu cần",
    "精神": "tinh thần",
    "整顿": "chỉnh đốn",
    "休息": "nghỉ ngơi",
    "整顿休息": "nghỉ ngơi chỉnh đốn",
    "营地": "trại",
    "营地教程": "hướng dẫn trại",
    "营地整顿": "chỉnh đốn trại",
    "营地杂务": "việc lặt vặt ở trại",
    "篝火夜话": "trò chuyện bên lửa trại",
    "篝火": "đống lửa",
    "夜话": "trò chuyện đêm",
    "夜谈": "trò chuyện đêm",
    "分享": "chia sẻ",
    "交换": "trao đổi",
    "心声": "tâm sự",
    "未来": "tương lai",
    "期望": "kỳ vọng",
    "温暖": "hơi ấm",
    "苦涩": "đắng cay",
    "奇怪玩意": "đồ kỳ quặc",
    "口粮": "lương thực",
    "相对干净": "tương đối sạch",
    "高能口粮": "lương thực giàu năng lượng",
    "回复": "hồi phục",
    "回复量": "lượng hồi phục",
    "医疗": "y tế",
    "急救": "sơ cứu",
    "急救包": "bộ sơ cứu",
    "标准急救包": "bộ sơ cứu tiêu chuẩn",
    "高级急救包": "bộ sơ cứu cao cấp",
    "夹板": "nẹp",
    "夹板包": "bộ nẹp",
    "标准夹板包": "bộ nẹp tiêu chuẩn",
    "高级夹板包": "bộ nẹp cao cấp",
    "修理包": "bộ sửa chữa",
    "修理箱": "hộp sửa chữa",
    "手术": "phẫu thuật",
    "修养身心": "tĩnh dưỡng thân tâm",
    "整顿休息后": "sau khi nghỉ ngơi chỉnh đốn",
    "自己": "bản thân",
    "时光荏苒": "thời gian thấm thoắt",
    "大失败": "đại thất bại",
    "大成功": "đại thành công",
    "成功": "thành công",
    "失败": "thất bại",
    "待初始化": "chờ khởi tạo",
    "主控": "chủ lực",
    "主控设定": "thiết lập chủ lực",
    "主控角色": "nhân vật chủ lực",
    "主角": "nhân vật chính",
    "小队": "đội",
    "小队名": "tên đội",
    "小队成员": "thành viên đội",
    "成员": "thành viên",
    "成员编辑模式": "chế độ chỉnh sửa thành viên",
    "成员去向": "hướng đi của thành viên",
    "当前事件": "sự kiện hiện tại",
    "当前内容": "nội dung hiện tại",
    "当前视角": "tầm nhìn hiện tại",
    "视角": "tầm nhìn",
    "视野": "tầm nhìn",
    "进入视野": "tiến vào tầm nhìn",
    "移入视野": "đưa vào tầm nhìn",
    "移除视野": "loại khỏi tầm nhìn",
    "异地": "nơi khác",
    "据点": "cứ điểm",
    "据点建设": "xây dựng cứ điểm",
    "据点防御": "phòng thủ cứ điểm",
    "据点设施": "công trình cứ điểm",
    "据点人口": "dân số cứ điểm",
    "据点财富": "tài phú cứ điểm",
    "据点统御": "thống trị cứ điểm",
    "局势": "cục diện",
    "往事": "chuyện cũ",
    "闲言": "lời đồn",
    "派系": "phe phái",
    "我方": "phe ta",
    "我方派系": "phe phái của ta",
    "我方派系名称": "tên phe phái của ta",
    "我方派系主旨": "tôn chỉ phe phái của ta",
    "我方派系规矩": "quy tắc phe phái của ta",
    "主旨": "tôn chỉ",
    "规矩": "quy tắc",
    "派系名称": "tên phe phái",
    "派系描述": "mô tả phe phái",
    "派系主旨": "tôn chỉ phe phái",
    "敌对": "thù địch",
    "友方": "phe ta",
    "友方派系": "phe thân thiện",
    "已知": "đã biết",
    "已知派系": "phe đã biết",
    "敌对派系": "phe thù địch",
    "敌对原因": "lý do thù địch",
    "结盟原因": "lý do liên minh",
    "态度": "thái độ",
    "关系": "quan hệ",
    "人际关系": "quan hệ nhân vật",
    "删除名单": "danh sách xóa",
    "击杀名单": "danh sách hạ sát",
    "死亡名单": "danh sách tử vong",
    "死亡名单移除": "loại khỏi danh sách tử vong",
    "记忆": "ký ức",
    "关键记忆": "ký ức then chốt",
    "遗忘": "quên",
    "遗忘关系": "quên quan hệ",
    "记录": "ghi chép",
    "纪录": "ghi chép",
    "日记": "nhật ký",
    "姓名": "họ tên",
    "名字": "tên",
    "名称": "tên gọi",
    "名称变更": "đổi tên gọi",
    "名称编辑": "chỉnh sửa tên gọi",
    "名称确认": "xác nhận tên gọi",
    "名字": "tên",
    "性别": "giới tính",
    "年龄": "tuổi",
    "身份": "thân phận",
    "外貌": "ngoại hình",
    "外貌描述": "mô tả ngoại hình",
    "体型": "dáng vóc",
    "身高": "chiều cao",
    "立场": "lập trường",
    "等级": "cấp độ",
    "经验": "kinh nghiệm",
    "经验值": "điểm kinh nghiệm",
    "升级所需": "cần để lên cấp",
    "属性": "thuộc tính",
    "属性点": "điểm thuộc tính",
    "特质": "đặc tính",
    "特质点": "điểm đặc tính",
    "临时特质": "đặc tính tạm thời",
    "创伤": "chấn thương",
    "血量": "máu",
    "最大": "tối đa",
    "负重": "tải trọng",
    "背包": "ba lô",
    "物品": "vật phẩm",
    "数量": "số lượng",
    "重量": "khối lượng",
    "价值": "giá trị",
    "分类": "phân loại",
    "子分类": "phân loại phụ",
    "品质": "phẩm chất",
    "种类": "loại",
    "种族": "chủng tộc",
    "主武器": "vũ khí chính",
    "副武器": "vũ khí phụ",
    "武器": "vũ khí",
    "装备": "trang bị",
    "护甲": "giáp",
    "武器材料": "vật liệu vũ khí",
    "护甲材料": "vật liệu giáp",
    "食物": "thức ăn",
    "饮品": "đồ uống",
    "医疗用品": "vật phẩm y tế",
    "科研道具": "đạo cụ nghiên cứu",
    "任务道具": "đạo cụ nhiệm vụ",
    "矿石": "quặng",
    "布料": "vải",
    "金属材料": "vật liệu kim loại",
    "农作物": "nông sản",
    "其他": "khác",
    "工具": "dụng cụ",
    "建筑": "công trình",
    "建筑材料": "vật liệu xây dựng",
    "设施": "công trình",
    "设施阵列": "dãy công trình",
    "仓库": "kho",
    "房屋": "nhà ở",
    "房屋": "nhà ở",
    "墙": "tường",
    "城墙": "tường thành",
    "防御墙": "tường phòng thủ",
    "防御建筑": "công trình phòng thủ",
    "炮塔": "tháp pháo",
    "弩炮": "nỏ pháo",
    "大门": "cổng lớn",
    "门": "cổng",
    "桥梁": "cầu",
    "炉": "lò",
    "织机": "khung cửi",
    "研究": "nghiên cứu",
    "工程图": "bản vẽ kỹ thuật",
    "蓝图": "bản thiết kế",
    "古代科技书": "sách công nghệ cổ đại",
    "生铁": "gang",
    "铁原板": "tấm sắt nguyên bản",
    "钢筋": "thép cốt",
    "电子元件": "linh kiện điện tử",
    "铜合金": "hợp kim đồng",
    "石材": "đá",
    "石砖": "gạch đá",
    "皮革": "da thuộc",
    "麻叶": "lá gai dầu",
    "大麻膏": "cao gai dầu",
    "酒": "rượu",
    "格洛格": "grog",
    "朗姆": "rum",
    "清酒": "sake",
    "面粉": "bột mì",
    "小麦": "lúa mì",
    "棉花": "bông",
    "肉": "thịt",
    "米饭": "cơm",
    "面包": "bánh mì",
    "水": "nước",
    "垃圾": "rác",
    "劣质品": "hàng kém chất lượng",
    "标准级": "tiêu chuẩn",
    "高级": "cao cấp",
    "标准": "tiêu chuẩn",
    "收益": "thu nhập",
    "每天最多访客": "số khách tối đa mỗi ngày",
    "每天": "mỗi ngày",
    "访客": "khách",
    "收益天数": "số ngày thu nhập",
    "资金": "tiền vốn",
    "财务": "tài chính",
    "财富": "tài phú",
    "人口": "dân số",
    "统御": "thống trị",
    "防御": "phòng thủ",
    "安全度": "độ an toàn",
    "生产": "sản xuất",
    "管理": "quản lý",
    "产量": "sản lượng",
    "收益": "thu nhập",
    "容量": "sức chứa",
    "范围": "phạm vi",
    "回合": "lượt",
    "次数": "số lần",
    "攻击次数": "số lần tấn công",
    "攻击": "tấn công",
    "攻击检定": "kiểm định tấn công",
    "防御检定": "kiểm định phòng thủ",
    "格挡检定": "kiểm định đỡ đòn",
    "闪避检定": "kiểm định né tránh",
    "闪避": "né tránh",
    "格挡": "đỡ đòn",
    "制服": "khống chế",
    "撤退": "rút lui",
    "逃跑": "bỏ chạy",
    "战斗结束": "kết thúc chiến đấu",
    "战斗中": "đang chiến đấu",
    "警戒": "cảnh giác",
    "逃跑中": "đang bỏ chạy",
    "确认删除任务": "xác nhận xóa nhiệm vụ",
    "删除任务": "xóa nhiệm vụ",
    "确认重命名": "xác nhận đổi tên",
    "确认合并": "xác nhận hợp nhất",
    "合并": "hợp nhất",
    "合并小队": "hợp nhất đội",
    "确认合并小队": "xác nhận hợp nhất đội",
    "营地系统": "hệ thống trại",
    "营地系统教程": "hướng dẫn hệ thống trại",
    "心情": "tâm trạng",
    "心情值": "điểm tâm trạng",
    "心情沉重": "tâm trạng nặng nề",
    "普通": "bình thường",
    "健康": "khỏe mạnh",
    "受伤": "bị thương",
    "严重下降": "giảm nghiêm trọng",
    "修理": "sửa chữa",
    "维修": "bảo trì",
    "部门": "bộ phận",
    "核心": "cốt lõi",
    "主旨": "tôn chỉ",
    "规矩": "quy tắc",
    "模型": "mô hình",
    "逻辑": "logic",
    "系统": "hệ thống",
    "规则详解": "giải thích quy tắc",
    "类别详解": "giải thích loại",
    "字面意思": "nghĩa đen",
    "自动选择": "tự động chọn",
    "选择": "chọn",
    "可用": "khả dụng",
    "未卖出": "chưa bán",
    "没卖出东西": "chưa bán được gì",
    "获得": "thu được",
    "失去": "mất",
    "消耗": "tiêu hao",
    "结果": "kết quả",
    "特殊": "đặc biệt",
    "特殊事件": "sự kiện đặc biệt",
    "命运事件": "sự kiện định mệnh",
    "事件": "sự kiện",
    "到来事件": "sự kiện đến",
    "日程": "lịch trình",
    "日期": "ngày",
    "今天": "hôm nay",
    "昨天": "hôm qua",
    "明天": "ngày mai",
    "下午": "buổi chiều",
    "上午": "buổi sáng",
    "晚上": "buổi tối",
    "中午": "buổi trưa",
    "天数": "số ngày",
    "时间": "thời gian",
    "世界": "thế giới",
    "区域": "khu vực",
    "城镇": "thị trấn",
    "所处位置": "vị trí đang ở",
    "所处地址": "địa chỉ hiện tại",
    "地址": "địa chỉ",
    "所在地": "nơi tọa lạc",
    "位置": "vị trí",
    "地图": "bản đồ",
    "地图搜索": "tìm kiếm bản đồ",
    "地点搜索": "tìm địa điểm",
    "重生镇": "Trấn Tái Sinh",
    "边缘镇": "Biên Giới Trấn",
    "眼窝镇": "Thị Trấn Hốc Mắt",
    "黑沙城": "Hắc Sa Thành",
    "世界尽头": "Tận Cùng Thế Giới",
    "废墟": "phế tích",
    "废土": "vùng đất hoang",
    "荒野": "vùng hoang dã",
    "荒漠": "sa mạc hoang",
    "沙漠": "sa mạc",
    "大沙漠": "Đại Sa Mạc",
    "奥克兰之谷": "Thung lũng Okran",
    "奥克兰之拳": "Nắm đấm Okran",
    "奥克兰之臂": "Cánh tay Okran",
    "奥克兰之傲": "Niềm kiêu hãnh Okran",
    "奥克兰之湾": "Vịnh Okran",
    "圣国": "Thánh Quốc",
    "联合城": "Liên Hợp Thành",
    "联合帝国": "Đế chế Liên Hợp",
    "赫夫特": "Heft",
    "赫夫特城": "thành Heft",
    "Heng": "Heng",
    "Bast": "Bast",
    "Shun": "Shun",
    "Squin": "Squin",
    "Vain": "Vain",
    "Leviathan": "Leviathan",
    "风暴之海岸": "Bờ biển Bão Táp",
    "北部海岸": "Bờ biển phía Bắc",
    "南部海岸": "Bờ biển phía Nam",
    "西部海岸": "Bờ biển phía Tây",
    "东部海岸": "Bờ biển phía Đông",
    "辛昆半岛": "Bán đảo Sinkun",
    "黑暗之指": "Ngón Tay Đen",
    "黑暗之臂": "Cánh tay Bóng Tối",
    "黑暗苍穹": "Bầu Trời U Ám",
    "白荒": "Bạch Hoang",
    "边境之地": "Vùng biên giới",
    "南方湿地": "đầm lầy phương nam",
    "洪泛地": "Vùng ngập lũ",
    "铁之谷": "Thung lũng Sắt",
    "铁之径": "Lối Sắt",
    "铁之蜘蛛": "nhện sắt",
    "蜘蛛工厂": "nhà máy nhện",
    "风蚀湖": "hồ phong thực",
    "沙尘暴": "bão cát",
    "酸雨": "mưa axit",
    "红雨": "mưa đỏ",
    "浓雾": "sương mù dày đặc",
    "雾岛": "Đảo Sương Mù",
    "虚荣": "Hư Vinh",
    "尖叫森林": "Rừng La Hét",
    "噬人": "ăn thịt người",
    "食人族": "bộ lạc ăn thịt người",
    "蜂巢族": "bộ tộc tổ ong",
    "沙克族": "người Shak",
    "沙克王国": "Vương quốc Shak",
    "沙克大剑": "đại kiếm Shak",
    "沙克之选": "Lựa Chọn của Shak",
    "海盗": "hải tặc",
    "商人": "thương nhân",
    "巡逻": "tuần tra",
    "巡逻队": "đội tuần tra",
    "领地": "lãnh thổ",
    "势力": "thế lực",
    "势力范围": "phạm vi thế lực",
    "主战场": "chiến trường chính",
    "缓冲带": "vùng đệm",
    "前线": "tiền tuyến",
    "堡垒": "pháo đài",
    "要塞": "cứ điểm",
    "军团": "quân đoàn",
    "秘密军事基地": "căn cứ quân sự bí mật",
    "军事基地": "căn cứ quân sự",
    "军事": "quân sự",
    "农民": "nông dân",
    "奴隶": "nô lệ",
    "奴隶主": "chủ nô",
    "奴隶商人": "thương nhân nô lệ",
    "反叛": "nổi dậy",
    "反蓄奴者": "quân chống nô lệ",
    "自由人": "người tự do",
    "野牛": "trâu hoang",
    "山羊": "dê núi",
    "加鲁兽": "Garru",
    "骨犬": "chó xương",
    "巨型": "khổng lồ",
    "巨兽": "cự thú",
    "喙嘴兽": "beak thing",
    "蟹": "cua",
    "蟹卵": "trứng cua",
    "喙嘴兽蛋": "trứng beak thing",
    "人口": "dân số",
    "村庄": "làng",
    "城镇": "thị trấn",
    "城市": "thành phố",
    "市镇": "thị trấn",
    "市民": "dân thị trấn",
    "大门": "cổng lớn",
    "门": "cổng",
    "桥": "cầu",
    "桥梁": "cầu",
    "桥梁通向": "cầu dẫn tới",
    "桥梁上方": "phía trên cầu",
    "古代遗迹": "di tích cổ đại",
    "遗迹": "di tích",
    "帝国遗产": "di sản đế quốc",
    "帝国": "đế quốc",
    "王城": "vương thành",
    "王国": "vương quốc",
    "皇宫": "hoàng cung",
    "皇帝": "hoàng đế",
    "贵族": "quý tộc",
    "领主": "lãnh chúa",
    "女王": "nữ vương",
    "王血": "vương huyết",
    "王座": "ngai vàng",
    "宫殿": "cung điện",
    "教国": "giáo quốc",
    "圣火": "thánh hỏa",
    "誓印": "ấn thề",
    "赐福": "ban phúc",
    "恶念": "ác niệm",
    "血蜘蛛": "nhện máu",
    "共生体": "cộng sinh thể",
    "副肢": "chi phụ",
    "长者": "trưởng lão",
    "幼体": "ấu thể",
    "成熟体": "thành thể",
    "狂战士": "cuồng chiến sĩ",
    "工匠": "thợ thủ công",
    "机魂": "cơ hồn",
    "渊胎": "thai vực sâu",
    "契印": "ấn khế ước",
    "暗夜圣痕": "thánh ngân đêm tối",
    "圣痕": "thánh ngân",
    "肯恩": "Ken",
    "比普": "Bip",
    "比拉克": "Birak",
    "克拉尔": "Kral",
    "奥克兰": "Okran",
    "娜尔可": "Narko",
    "比普": "Bip",
    "罪恶": "tội lỗi",
    "深渊": "vực sâu",
    "虚无": "hư vô",
    "饥肠辘辘": "đói khát cồn cào",
    "心脏": "trái tim",
    "双手": "hai tay",
    "双足": "hai chân",
    "伙伴": "bạn đồng hành",
    "挚友": "bạn thân",
    "爱人": "người yêu",
    "同伴": "đồng đội",
    "队伍": "đội",
    "队伍里": "trong đội",
    "队伍中": "trong đội",
    "队伍最高": "cao nhất đội",
    "队伍的": "của đội",
    "主导": "chủ đạo",
    "主导权": "quyền chủ đạo",
    "权力": "quyền lực",
    "金钱": "tiền bạc",
    "财富": "tài phú",
    "利益": "lợi ích",
    "货币": "tiền tệ",
    "商业": "thương mại",
    "商会": "thương hội",
    "商人会": "hội thương nhân",
    "粮食": "lương thực",
    "书本": "sách vở",
    "论文": "luận văn",
    "研究所": "viện nghiên cứu",
    "研究员": "nhà nghiên cứu",
    "科学家": "nhà khoa học",
    "机械": "cơ khí",
    "机械人": "người máy",
    "机器人": "người máy",
    "兽人": "thú nhân",
    "人类": "nhân loại",
    "骨人": "người xương",
    "人皮蜘蛛": "nhện da người",
    "废墟科技猎人": "thợ săn công nghệ phế tích",
    "科技": "công nghệ",
    "道路": "đường",
    "桥梁": "cầu",
    "通道": "lối đi",
    "视角": "góc nhìn",
    "渲染": "kết xuất",
    "加载": "tải",
    "地图": "bản đồ",
    "区域": "khu vực",
    "方位": "phương hướng",
    "方向": "hướng",
    "南北": "nam bắc",
    "东西": "đông tây",
    "东北": "đông bắc",
    "西北": "tây bắc",
    "西南": "tây nam",
    "东南": "đông nam",
    "北部": "phía bắc",
    "南部": "phía nam",
    "西部": "phía tây",
    "东部": "phía đông",
    "中心": "trung tâm",
    "核心": "cốt lõi",
    "缓冲区": "vùng đệm",
    "平原": "đồng bằng",
    "高原": "cao nguyên",
    "山谷": "thung lũng",
    "山地": "vùng núi",
    "丘陵": "đồi núi",
    "湿地": "đầm lầy",
    "沼泽": "đầm lầy",
    "海湾": "vịnh",
    "海岸": "bờ biển",
    "半岛": "bán đảo",
    "岛": "đảo",
    "森林": "rừng",
    "沙丘": "cồn cát",
    "岩石": "đá",
    "山脉": "dãy núi",
    "河谷": "thung lũng sông",
    "河流": "dòng sông",
    "湖泊": "hồ nước",
    "沼地": "đầm lầy",
    "废墟群": "cụm phế tích",
    "缓冲": "đệm",
    "遗民": "người sống sót",
    "幸存者": "người sống sót",
    "营火": "lửa trại",
    "巡哨": "tuần gác",
    "防御系统": "hệ thống phòng thủ",
    "生产体系": "hệ thống sản xuất",
    "管理体系": "hệ thống quản lý",
    "旅馆": "quán trọ",
    "商店": "cửa hàng",
    "市场": "chợ",
    "流通": "lưu thông",
    "税收": "thu thuế",
    "贫瘠": "cằn cỗi",
    "荒废": "hoang phế",
    "废弃": "bỏ hoang",
    "废土": "vùng đất hoang",
    "灰白": "xám trắng",
    "毒气": "khí độc",
    "污染": "ô nhiễm",
    "工业": "công nghiệp",
    "棘刺": "gai nhọn",
    "石质": "đá",
    "灰烬": "tro tàn",
    "风沙": "gió cát",
    "水源": "nguồn nước",
    "地形": "địa hình",
    "地貌": "địa mạo",
    "气候": "khí hậu",
    "环境": "môi trường",
    "景观": "cảnh quan",
    "生物": "sinh vật",
    "野兽": "dã thú",
    "危险": "nguy hiểm",
    "机遇": "cơ hội",
    "威胁": "đe dọa",
    "收获": "thu hoạch",
    "产物": "sản vật",
    "产地": "nơi sản xuất",
    # Mảnh còn sót từ trạng thái / bản đồ
    "小型": "nhỏ",
    "成熟": "trưởng thành",
    "稳定": "ổn định",
    "常驻": "thường trú",
    "影响力": "ảnh hưởng",
    "权力中心": "trung tâm quyền lực",
    "城镇级": "cấp thị trấn",
    "村庄级": "cấp làng",
    "哨站": "đồn gác",
    "前哨": "tiền đồn",
    "驻守": "đồn trú",
    "驻扎": "đóng quân",
    "建成": "hoàn thành",
    "未建成": "chưa xây xong",
    "人员编制": "biên chế nhân sự",
    "外来者": "người ngoài",
    "补给": "tiếp tế",
    "商队": "đoàn thương nhân",
    "商路": "thương lộ",
    "货物": "hàng hóa",
    "货币": "tiền tệ",
    "税收": "thu thuế",
    "领地": "lãnh địa",
    "领主": "lãnh chúa",
    "帝国遗产": "di sản đế quốc",
    "帝国领地": "lãnh địa đế quốc",
    "军事基地": "căn cứ quân sự",
    "秘密": "bí mật",
    "道场": "võ đường",
    "寺庙": "ngôi đền",
    "工厂": "nhà máy",
    "实验室": "phòng thí nghiệm",
    "工坊": "xưởng",
    "农场": "nông trại",
    "港口": "cảng",
    "港": "cảng",
    "河流": "dòng sông",
    "河谷": "thung lũng sông",
    "峡谷": "hẻm núi",
    "山脉": "dãy núi",
    "山地": "vùng núi",
    "平原": "đồng bằng",
    "草原": "thảo nguyên",
    "沼泽": "đầm lầy",
    "沼地": "đầm lầy",
    "湿地": "đầm lầy",
    "海岸": "bờ biển",
    "海湾": "vịnh",
    "海域": "hải vực",
    "半岛": "bán đảo",
    "岛": "đảo",
    "森林": "rừng",
    "荒原": "hoang nguyên",
    "荒地": "đất hoang",
    "废墟": "phế tích",
    "废土": "vùng đất hoang",
    "沙漠": "sa mạc",
    "沙丘": "cồn cát",
    "沙尘暴": "bão cát",
    "酸雨": "mưa axit",
    "红雨": "mưa đỏ",
    "浓雾": "sương mù dày đặc",
    "污染": "ô nhiễm",
    "工业": "công nghiệp",
    "军团": "quân đoàn",
    "巡逻队": "đội tuần tra",
    "巡逻": "tuần tra",
    "商人": "thương nhân",
    "猎人": "thợ săn",
    "赏金猎人": "thợ săn tiền thưởng",
    "科技猎人": "thợ săn công nghệ",
    "自由人": "người tự do",
    "奴隶商人": "thương nhân nô lệ",
    "奴隶": "nô lệ",
    "农民": "nông dân",
    "贵族": "quý tộc",
    "圣火": "thánh hỏa",
    "秩序": "trật tự",
    "信仰": "đức tin",
    "守备": "phòng thủ",
    "防御体系": "hệ thống phòng thủ",
    "生产体系": "hệ thống sản xuất",
    "管理体系": "hệ thống quản lý",
    "权力": "quyền lực",
    "中心": "trung tâm",
    "大型": "lớn",
    "中型": "trung",
    "小型": "nhỏ",
    "稳定": "ổn định",
    "常驻": "thường trú",
    "影响": "ảnh hưởng",
    "影响力": "ảnh hưởng",
    "规模": "quy mô",
    "成熟": "trưởng thành",
    "荒废": "hoang phế",
    "废弃": "bỏ hoang",
    "固定": "cố định",
    "暂时": "tạm thời",
    "已知": "đã biết",
    "未知": "không rõ",
    "待定": "chờ định",
    "已固定": "đã cố định",
    "当前": "hiện tại",
    "暂无": "hiện chưa có",
    "待初始化": "chờ khởi tạo",
    "主控": "chủ lực",
    "主角": "nhân vật chính",
    "角色": "nhân vật",
    "角色数据": "dữ liệu nhân vật",
    "状态栏": "thanh trạng thái",
    "类型": "kiểu",
    "类别": "loại",
    "武术类": "loại võ thuật",
    "军刀类": "loại quân đao",
    "大型类": "loại vũ khí lớn",
    "弓": "cung",
    "弩": "nỏ",
    "空手": "tay không",
    "无甲": "không giáp",
    "无派系": "không phe phái",
    "正常": "bình thường",
    "正面效果": "hiệu quả tích cực",
    "负面效果": "hiệu quả tiêu cực",
    "消除": "xóa",
    "队伍": "đội",
    "主任务状态": "trạng thái nhiệm vụ chính",
    "规则": "quy tắc",
    "规则详解": "giải thích quy tắc",
    "击杀名单": "danh sách hạ sát",
    "日记": "nhật ký",
    "记忆": "ký ức",
    "记录": "ghi chép",
    "删除": "xóa",
    "删除小队": "xóa đội",
    "无法删除": "không thể xóa",
    "退出全屏": "thoát toàn màn hình",
    "全屏": "toàn màn hình",
    "新建Cứ điểm": "xây dựng cứ điểm mới",
    "Cứ điểm建设": "xây dựng cứ điểm",
    "Cứ điểm防御": "phòng thủ cứ điểm",
    "Cứ điểm设施": "công trình cứ điểm",
    "Cứ điểm人口": "dân số cứ điểm",
    "Cứ điểm财富": "tài phú cứ điểm",
    "Cứ điểm统御": "thống trị cứ điểm",
    "Cứ điểm": "cứ điểm",
    "Thế giới": "thế giới",
    "Số ngày": "số ngày",
    "Thời gian": "thời gian",
    "Sự kiện hiện tại": "sự kiện hiện tại",
    "Tên phe phái của ta": "tên phe phái của ta",
    "Thành viên đội": "thành viên đội",
    "Vị trí đang ở": "vị trí đang ở",
    "Khu vực": "khu vực",
    "Thị trấn": "thị trấn",
    "Tầm nhìn": "tầm nhìn",
    "Nơi khác": "nơi khác",
    "Cục diện": "cục diện",
    "Chuyện cũ": "chuyện cũ",
    "Lời đồn": "lời đồn",
    "Tiền": "tiền",
}


CHARMAP = {
    "的": "của",
    "了": "",
    "在": "ở",
    "是": "là",
    "和": "và",
    "与": "và",
    "及": "và",
    "这": "này",
    "這": "này",
    "那": "kia",
    "其": "của nó",
    "由": "do",
    "为": "là",
    "為": "là",
    "会": "sẽ",
    "會": "sẽ",
    "但": "nhưng",
    "也": "cũng",
    "以": "bằng",
    "从": "từ",
    "從": "từ",
    "到": "đến",
    "对": "đối",
    "對": "đối",
    "向": "về",
    "里": "trong",
    "裡": "trong",
    "中": "trung",
    "上": "trên",
    "下": "dưới",
    "前": "trước",
    "后": "sau",
    "後": "sau",
    "左": "trái",
    "右": "phải",
    "北": "bắc",
    "南": "nam",
    "东": "đông",
    "東": "đông",
    "西": "tây",
    "大": "lớn",
    "小": "nhỏ",
    "多": "nhiều",
    "少": "ít",
    "高": "cao",
    "低": "thấp",
    "新": "mới",
    "旧": "cũ",
    "舊": "cũ",
    "古": "cổ",
    "现": "hiện",
    "現": "hiện",
    "已": "đã",
    "未": "chưa",
    "无": "không",
    "無": "không",
    "有": "có",
    "可": "có thể",
    "能": "có thể",
    "不": "không",
    "被": "bị",
    "将": "sẽ",
    "將": "sẽ",
    "这": "này",
    "些": "những",
    "个": "cái",
    "個": "cái",
    "位": "vị",
    "于": "ở",
    "於": "ở",
    "区": "khu",
    "區": "khu",
    "域": "vực",
    "材": "vật liệu",
    "料": "liệu",
    "表": "bảng",
    "值": "giá trị",
    "量": "lượng",
    "属": "thuộc",
    "屬": "thuộc",
    "性": "tính",
    "技": "kỹ",
    "能": "năng",
    "级": "cấp",
    "級": "cấp",
    "阶": "giai đoạn",
    "階": "giai đoạn",
    "层": "tầng",
    "層": "tầng",
    "态": "thái",
    "態": "thái",
    "状": "trạng",
    "狀": "trạng",
    "变": "biến",
    "變": "biến",
    "编": "biên",
    "編": "biên",
    "辑": "tập",
    "輯": "tập",
    "改": "sửa",
    "修": "sửa",
    "写": "viết",
    "寫": "viết",
    "减": "giảm",
    "減": "giảm",
    "增": "tăng",
    "损": "tổn",
    "損": "tổn",
    "伤": "thương",
    "傷": "thương",
    "害": "hại",
    "回": "hồi",
    "復": "phục",
    "复": "phục",
    "合": "hợp",
    "分": "phân",
    "支": "chi",
    "节": "tiết",
    "節": "tiết",
    "目": "mục",
    "标": "tiêu",
    "標": "tiêu",
    "记": "ký",
    "記": "ký",
    "录": "lục",
    "錄": "lục",
    "续": "tiếp",
    "續": "tiếp",
    "产": "sản",
    "產": "sản",
    "出": "xuất",
    "消": "tiêu",
    "耗": "hao",
    "护": "hộ",
    "護": "hộ",
    "防": "phòng",
    "御": "ngự",
    "攻": "công",
    "击": "kích",
    "擊": "kích",
    "锈": "rỉ",
    "鏽": "rỉ",
    "剑": "kiếm",
    "劍": "kiếm",
    "棍": "gậy",
    "甲": "giáp",
    "布": "vải",
    "鞋": "giày",
    "衫": "áo",
    "皮": "da",
    "刀": "đao",
    "弓": "cung",
    "弩": "nỏ",
    "枪": "thương",
    "槍": "thương",
    "刃": "lưỡi",
    "斧": "rìu",
    "锤": "búa",
    "鎚": "búa",
    "头": "đầu",
    "頭": "đầu",
    "手": "tay",
    "脚": "chân",
    "腳": "chân",
    "腿": "chân",
    "臂": "tay",
    "胸": "ngực",
    "身": "thân",
    "体": "thể",
    "體": "thể",
    "心": "tim",
    "灵": "linh",
    "靈": "linh",
    "魂": "hồn",
    "肉": "thịt",
    "血": "máu",
    "骨": "xương",
    "筋": "gân",
    "膜": "màng",
    "耳": "tai",
    "眼": "mắt",
    "鼻": "mũi",
    "嘴": "miệng",
    "口": "miệng",
    "食": "thực",
    "饮": "ẩm",
    "飮": "ẩm",
    "饭": "cơm",
    "飯": "cơm",
    "药": "thuốc",
    "藥": "thuốc",
    "急": "cấp",
    "救": "cứu",
    "夹": "kẹp",
    "夾": "kẹp",
    "板": "bản",
    "修": "sửa",
    "理": "lý",
    "包": "gói",
    "战": "chiến",
    "戰": "chiến",
    "斗": "đấu",
    "初": "sơ",
    "始": "thỉ",
    "局": "cục",
    "剧": "kịch",
    "劇": "kịch",
    "本": "bản",
    "专": "chuyên",
    "專": "chuyên",
    "属": "thuộc",
    "隶": "lệ",
    "隸": "lệ",
    "随": "tùy",
    "隨": "tùy",
    "机": "cơ",
    "機": "cơ",
    "随机": "ngẫu nhiên",
    "重": "trọng",
    "抽": "rút",
    "自": "tự",
    "定": "định",
    "义": "nghĩa",
    "義": "nghĩa",
    "选": "chọn",
    "選": "chọn",
    "项": "mục",
    "項": "mục",
    "问": "vấn",
    "問": "vấn",
    "答": "đáp",
    "难": "khó",
    "難": "khó",
    "易": "dễ",
    "极": "cực",
    "極": "cực",
    "困": "khốn",
    "厄": "ách",
    "危": "nguy",
    "险": "hiểm",
    "險": "hiểm",
    "梦": "mộng",
    "夢": "mộng",
    "想": "tưởng",
    "魂": "hồn",
    "气": "khí",
    "模": "mô",
    "板": "bản",
    "仅": "chỉ",
    "维": "duy",
    "世": "thế",
    "界": "giới",
    "背": "bối",
    "景": "cảnh",
    "故": "cố",
    "事": "sự",
    "式": "thức",
    "文": "văn",
    "字": "tự",
    "页": "trang",
    "面": "diện",
    "效": "hiệu",
    "果": "quả",
    "输": "nhập",
    "入": "nhập",
    "导": "dẫn",
    "出": "xuất",
    "保": "bảo",
    "存": "tồn",
    "删": "xóa",
    "除": "loại bỏ",
    "重": "trọng",
    "命": "mệnh",
    "名": "danh",
    "测": "trắc",
    "試": "thử",
    "试": "thử",
    "发": "phát",
    "布": "bố",
    "本": "bản",
    "地": "địa",
    "外": "ngoại",
    "部": "bộ",
    "链": "liên",
    "鏈": "liên",
    "接": "kết",
    "网": "võng",
    "網": "võng",
    "站": "trạm",
    "全": "toàn",
    "部": "bộ",
    "主": "chủ",
    "副": "phụ",
    "前": "tiền",
    "后": "hậu",
    "後": "hậu",
    "启": "khải",
    "啟": "khải",
    "停": "đình",
    "止": "chỉ",
    "显": "hiển",
    "示": "thị",
    "隐": "ẩn",
    "隱": "ẩn",
    "藏": "tàng",
    "开": "khai",
    "開": "khai",
    "关": "quan",
    "關": "quan",
    "启用": "khởi động",
    "禁": "cấm",
    "用": "dùng",
    "设": "thiết",
    "置": "đặt",
    "防": "phòng",
    "御": "ngự",
    "伤": "thương",
    "害": "hại",
    "命": "mệnh",
    "中": "trúng",
    "闪": "lánh",
    "閃": "lánh",
    "避": "né",
    "格": "cách",
    "挡": "đỡ",
    "擋": "đỡ",
    "判": "phán",
    "定": "định",
    "回": "hồi",
    "合": "hợp",
    "阈": "ngưỡng",
    "閾": "ngưỡng",
    "值": "giá trị",
    "速": "tốc",
    "率": "tỷ lệ",
    "差": "chênh",
    "攻": "công",
    "击": "kích",
    "擊": "kích",
    "战": "chiến",
    "戰": "chiến",
    "术": "thuật",
    "術": "thuật",
    "结": "kết",
    "算": "toán",
    "层": "tầng",
    "層": "tầng",
    "段": "đoạn",
    "计": "kế",
    "計": "kế",
    "条": "điều",
    "條": "điều",
    "规": "quy",
    "規": "quy",
    "则": "tắc",
    "則": "tắc",
    "伤害": "thương tổn",
    "防御": "phòng thủ",
    "攻击": "tấn công",
    "闪避": "né tránh",
    "格挡": "đỡ đòn",
    "判定": "kiểm định",
    "回合": "lượt",
    "结束": "kết thúc",
    "结束战斗": "kết thúc chiến đấu",
    "战斗": "chiến đấu",
    "医疗": "y tế",
    "治疗": "chữa trị",
    "回复": "hồi phục",
    "修理": "sửa chữa",
    "后勤": "hậu cần",
    "训练": "huấn luyện",
    "营地": "trại",
    "教程": "hướng dẫn",
    "惩罚": "hình phạt",
    "奖励": "phần thưởng",
    "提升": "tăng cường",
    "消耗": "tiêu hao",
    "获得": "thu được",
    "失去": "mất",
    "降低": "giảm",
    "增加": "tăng",
    "减少": "giảm",
    "影响": "ảnh hưởng",
    "管理": "quản lý",
    "氣": "khí",
    "治": "trị",
    "疗": "liệu",
    "療": "liệu",
    "营": "trại",
    "營": "trại",
    "训": "huấn",
    "訓": "huấn",
    "练": "luyện",
    "練": "luyện",
    "学": "học",
    "學": "học",
    "务": "vụ",
    "務": "vụ",
    "问": "vấn",
    "問": "vấn",
    "题": "đề",
    "題": "đề",
    "栏": "cột",
    "欄": "cột",
    "页": "trang",
    "頁": "trang",
    "图": "đồ",
    "圖": "đồ",
    "案": "án",
    "件": "kiện",
    "库": "khố",
    "庫": "khố",
    "馆": "viện",
    "館": "viện",
    "城": "thành",
    "镇": "trấn",
    "鎮": "trấn",
    "村": "làng",
    "岛": "đảo",
    "島": "đảo",
    "关": "quan",
    "關": "quan",
    "海": "biển",
    "山": "núi",
    "谷": "thung lũng",
    "河": "sông",
    "湖": "hồ",
    "湾": "vịnh",
    "灣": "vịnh",
    "沙": "cát",
    "林": "rừng",
    "森": "rừng",
    "田": "ruộng",
    "荒": "hoang",
    "废": "phế",
    "廢": "phế",
    "雨": "mưa",
    "雾": "sương mù",
    "霧": "sương mù",
    "风": "gió",
    "風": "gió",
    "冰": "băng",
    "火": "lửa",
    "岩": "đá",
    "石": "đá",
    "土": "đất",
    "黄": "vàng",
    "黃": "vàng",
    "黑": "đen",
    "白": "trắng",
    "红": "đỏ",
    "紅": "đỏ",
    "蓝": "xanh lam",
    "藍": "xanh lam",
    "绿": "xanh lục",
    "綠": "xanh lục",
    "紫": "tím",
    "灰": "xám",
    "定": "định",
    "置": "đặt",
    "改": "sửa",
    "编": "biên",
    "輯": "tập",
    "辑": "tập",
    "输": "nhập",
    "輸": "nhập",
    "入": "nhập",
    "删": "xóa",
    "刪": "xóa",
    "除": "loại bỏ",
    "提": "đề",
    "交": "giao",
    "调": "điều",
    "調": "điều",
    "整": "chỉnh",
    "请": "vui lòng",
    "請": "vui lòng",
    "求": "cầu",
    "确": "xác",
    "確": "xác",
    "认": "nhận",
    "認": "nhận",
    "选": "chọn",
    "選": "chọn",
    "择": "chọn",
    "擇": "chọn",
    "换": "thay",
    "換": "thay",
    "切": "cắt",
    "标": "đánh dấu",
    "記": "ký",
    "记": "ký",
    "录": "lục",
    "录": "lục",
    "传": "truyền",
    "傳": "truyền",
    "闻": "văn",
    "聞": "văn",
    "设": "thiết",
    "設": "thiết",
    "锁": "khóa",
    "鎖": "khóa",
    "闭": "đóng",
    "閉": "đóng",
    "开": "mở",
    "開": "mở",
    "同": "đồng",
    "步": "bộ",
    "结": "kết",
    "果": "quả",
    "完": "hoàn",
    "成": "thành",
    "失": "thất",
    "败": "bại",
    "敗": "bại",
    "可": "có thể",
    "用": "dùng",
    "無": "không",
    "无": "không",
    "法": "pháp",
    "暂": "tạm",
    "暫": "tạm",
    "时": "thời",
    "時": "thời",
    "主": "chủ",
    "控": "khống",
    "角": "giác",
    "队": "đội",
    "員": "viên",
    "员": "viên",
    "村": "làng",
    "庄": "trại",
    "莊": "trại",
    "城": "thành",
    "市": "thị",
    "点": "điểm",
    "點": "điểm",
    "视": "thị",
    "視": "thị",
    "野": "dã",
    "异": "dị",
    "異": "dị",
    "局": "cục",
    "势": "thế",
    "勢": "thế",
    "往": "vãng",
    "事": "sự",
    "闲": "nhàn",
    "閒": "nhàn",
    "日": "nhật",
    "志": "chí",
    "档": "đảng",
    "檔": "đảng",
    "案": "án",
    "文": "văn",
    "件": "kiện",
    "图": "đồ",
    "圖": "đồ",
    "像": "tượng",
    "军": "quân",
    "軍": "quân",
    "械": "khí",
    "库": "khố",
    "庫": "khố",
    "馆": "viện",
    "館": "viện",
    "神": "thần",
    "秘": "bí",
    "陆": "lục",
    "陸": "lục",
    "海": "hải",
    "岸": "ngạn",
    "半": "bán",
    "岛": "đảo",
    "島": "đảo",
    "山": "sơn",
    "谷": "cốc",
    "平": "bình",
    "原": "nguyên",
    "湿": "thấp",
    "濕": "thấp",
    "沼": "đầm",
    "泽": "trạch",
    "澤": "trạch",
    "森": "sâm",
    "林": "lâm",
    "沙": "sa",
    "漠": "mạc",
    "风": "phong",
    "風": "phong",
    "暴": "bạo",
    "口": "khẩu",
    "之": "chi",
    "指": "chỉ",
    "拳": "quyền",
    "臂": "tí",
    "地": "địa",
    "区": "khu",
    "區": "khu",
    "域": "vực",
    "环": "vòng",
    "環": "vòng",
    "塔": "tháp",
    "门": "cổng",
    "門": "cổng",
    "墙": "tường",
    "牆": "tường",
    "堡": "pháo đài",
    "宫": "cung",
    "宮": "cung",
    "殿": "điện",
    "皇": "hoàng",
    "帝": "đế",
    "王": "vương",
    "主": "chủ",
    "首": "thủ",
    "军": "quân",
    "軍": "quân",
    "兵": "binh",
    "士": "sĩ",
    "商": "thương",
    "工": "công",
    "农": "nông",
    "農": "nông",
    "猎": "săn",
    "獵": "săn",
    "研": "nghiên",
    "究": "cứu",
    "技": "kỹ",
    "术": "thuật",
    "術": "thuật",
    "学": "học",
    "學": "học",
    "家": "gia",
    "族": "tộc",
    "帮": "bang",
    "幫": "bang",
    "派": "phái",
    "盟": "liên minh",
    "部": "bộ",
    "落": "lạc",
    "记": "ký",
    "記": "ký",
    "录": "lục",
    "錄": "lục",
    "报": "báo",
    "報": "báo",
    "告": "cáo",
    "事": "việc",
    "物": "vật",
    "品": "phẩm",
    "质": "chất",
    "質": "chất",
    "类": "loại",
    "類": "loại",
    "型": "kiểu",
    "场": "sân",
    "場": "sân",
    "店": "cửa hàng",
    "旅": "lữ",
    "客": "khách",
    "船": "thuyền",
    "桥": "cầu",
    "橋": "cầu",
    "路": "đường",
    "道": "đạo",
    "港": "cảng",
    "站": "trạm",
    "點": "điểm",
    "点": "điểm",
    "线": "tuyến",
    "線": "tuyến",
    "副": "phụ",
    "临": "lâm",
    "臨": "lâm",
    "强": "mạnh",
    "強": "mạnh",
    "弱": "yếu",
    "满": "đầy",
    "滿": "đầy",
    "空": "trống",
    "空": "trống",
    "长": "dài",
    "長": "dài",
    "短": "ngắn",
    "厚": "dày",
    "薄": "mỏng",
    "重": "nặng",
    "輕": "nhẹ",
    "轻": "nhẹ",
    "热": "nóng",
    "熱": "nóng",
    "冷": "lạnh",
    "快": "nhanh",
    "慢": "chậm",
    "稳": "ổn định",
    "穩": "ổn định",
    "名": "tên",
    "数": "số",
    "數": "số",
    "最": "nhất",
    "很": "rất",
    "更": "hơn",
    "再": "lại",
    "再": "lại",
    "次": "lần",
    "每": "mỗi",
    "天": "ngày",
    "日": "ngày",
    "月": "tháng",
    "年": "năm",
    "时": "giờ",
    "時": "giờ",
    "替": "thay thế",
    "库": "kho",
    "館": "viện",
    "馆": "viện",
    "械": "khí",
    "书": "sách",
    "裝": "trang",
    "装": "trang",
    "修": "sửa",
    "台": "đài",
    "设": "thiết",
    "設": "thiết",
    "标": "đánh dấu",
    "標": "đánh dấu",
    "栏": "cột",
    "欄": "cột",
    "营": "trại",
    "營": "trại",
    "练": "luyện",
    "練": "luyện",
    "训": "huấn",
    "訓": "huấn",
    "祈": "cầu nguyện",
    "祷": "khấn",
    "綱": "cương",
    "纲": "cương",
    "志": "chí",
    "册": "sách",
    "冊": "sách",
    "章": "chương",
    "图": "đồ",
    "圖": "đồ",
    "陆": "lục",
    "陸": "lục",
    "地": "địa",
    "勢": "thế",
    "势": "thế",
    "範": "phạm",
    "范": "phạm",
    "圍": "vi",
    "围": "vi",
    "緩": "hoãn",
    "缓": "hoãn",
    "衝": "xung",
    "冲": "xung",
    "帶": "đai",
    "带": "đai",
    "戰": "chiến",
    "战": "chiến",
    "場": "trường",
    "场": "trường",
    "發": "phát",
    "发": "phát",
    "展": "triển",
    "遺": "di",
    "遗": "di",
    "跡": "tích",
    "迹": "tích",
    "連": "liên",
    "连": "liên",
    "接": "nối",
    "穿": "xuyên",
    "越": "vượt",
    "經": "kinh",
    "经": "kinh",
    "久": "lâu",
    "絕": "tuyệt",
    "绝": "tuyệt",
    "罩": "bao phủ",
    "籠": "lồng",
    "笼": "lồng",
    "覆": "phủ",
    "仍": "vẫn",
    "然": "rồi",
    "常": "thường",
    "適": "thích hợp",
    "适": "thích hợp",
    "居": "cư",
    "住": "trú",
    "產": "sản",
    "产": "sản",
    "礦": "quặng",
    "矿": "quặng",
    "業": "nghiệp",
    "业": "nghiệp",
    "管": "quản",
    "理": "lý",
    "隊": "đội",
    "队": "đội",
    "民": "dân",
    "人": "người",
    "神": "thần",
    "秘": "bí",
    "失": "thất",
    "落": "lạc",
    "軍": "quân",
    "军": "quân",
    "械": "khí",
    "庫": "khố",
    "馆": "viện",
    "書": "sách",
    "书": "sách",
    "傳": "truyền",
    "传": "truyền",
    "聞": "văn",
    "闻": "văn",
    "規": "quy",
    "规": "quy",
    "則": "tắc",
    "则": "tắc",
    "命": "mệnh",
    "脈": "mạch",
    "脉": "mạch",
    "學": "học",
    "学": "học",
    "會": "hội",
    "会": "hội",
    "雜": "tạp",
    "杂": "tạp",
    "亂": "loạn",
    "乱": "loạn",
    "剩": "thừa",
    "余": "dư",
    "擁": "ôm",
    "拥": "ôm",
    "輝": "quang",
    "辉": "quang",
    "威": "uy",
    "脅": "hiếp",
    "胁": "hiếp",
    "侵": "xâm",
    "守": "thủ",
    "備": "bị",
    "备": "bị",
    "治": "trị",
    "統": "thống",
    "统": "thống",
    "御": "ngự",
    "務": "vụ",
    "务": "vụ",
    "軍": "quân",
    "兵": "binh",
    "主": "chủ",
    "首": "thủ",
    "正": "chính",
    "反": "phản",
    "黑": "đen",
    "白": "trắng",
    "红": "đỏ",
    "紅": "đỏ",
    "绿": "xanh lục",
    "綠": "xanh lục",
    "蓝": "xanh lam",
    "藍": "xanh lam",
    "紫": "tím",
    "灰": "xám",
}

CHARMAP.update({
    "兰": "Lan",
    "奧": "O",
    "奥": "O",
    "聯": "liên",
    "联": "liên",
    "足": "đủ",
    "賜": "ban",
    "赐": "ban",
    "電": "điện",
    "电": "điện",
    "跑": "chạy",
    "獲": "thu được",
    "获": "thu được",
    "元": "nguyên",
    "觸": "chạm",
    "触": "chạm",
    "器": "thiết bị",
    "精": "tinh",
    "鍛": "rèn",
    "锻": "rèn",
    "硬": "cứng",
    "徹": "thấu",
    "彻": "thấu",
    "檢": "kiểm",
    "检": "kiểm",
    "互": "lẫn nhau",
    "肌": "cơ",
    "配": "phối",
    "喙": "mỏ",
    "雙": "đôi",
    "双": "đôi",
    "念": "ý nghĩ",
    "築": "xây",
    "筑": "xây",
    "額": "trán",
    "额": "trán",
    "若": "nếu",
    "美": "đẹp",
    "微": "nhỏ",
    "軀": "thân xác",
    "躯": "thân xác",
    "虛": "hư",
    "虚": "hư",
    "例": "ví dụ",
    "醫": "y",
    "医": "y",
    "升": "tăng",
    "雖": "dù",
    "虽": "dù",
    "降": "hạ",
    "娜": "Na",
    "殊": "đặc biệt",
    "轉": "chuyển",
    "转": "chuyển",
    "載": "chở",
    "载": "chở",
    "順": "thuận",
    "顺": "thuận",
    "優": "ưu",
    "优": "ưu",
    "躲": "trốn",
    "益": "ích",
    "架": "giá đỡ",
    "賣": "bán",
    "卖": "bán",
    "註": "chú",
    "注": "chú",
    "房": "nhà",
    "爆": "nổ",
    "查": "tra",
    "況": "tình huống",
    "况": "tình huống",
    "響": "vang",
    "响": "vang",
    "拼": "liều ghép",
    "尚": "vẫn",
    "驗": "nghiệm",
    "验": "nghiệm",
    "恢": "khôi phục",
    "勞": "lao",
    "劳": "lao",
    "淵": "vực sâu",
    "渊": "vực sâu",
    "撕": "xé",
    "給": "cho",
    "给": "cho",
    "絲": "sợi",
    "丝": "sợi",
    "糧": "lương thực",
    "粮": "lương thực",
    "敲": "gõ",
    "驚": "kinh ngạc",
    "惊": "kinh ngạc",
    "錯": "sai",
    "错": "sai",
    "淨": "sạch",
    "净": "sạch",
    "樂": "vui",
    "乐": "vui",
    "即": "tức thì",
    "邏": "logic",
    "逻": "logic",
    "騎": "kỵ",
    "骑": "kỵ",
    "塊": "khối",
    "块": "khối",
    "骰": "xúc xắc",
    "鋒": "mũi nhọn",
    "锋": "mũi nhọn",
    "罪": "tội",
    "遍": "khắp",
    "繃": "căng",
    "绷": "căng",
    "嘗": "thử",
    "尝": "thử",
    "棒": "gậy",
    "候": "chờ",
    "核": "lõi",
    "觀": "quan sát",
    "观": "quan sát",
    "傲": "kiêu",
    "握": "nắm",
    "緣": "mép",
    "缘": "mép",
    "脫": "thoát",
    "脱": "thoát",
    "蠻": "man",
    "蛮": "man",
    "射": "bắn",
    "輪": "vòng",
    "轮": "vòng",
    "吸": "hút",
    "扎": "đâm",
    "拒": "từ chối",
    "愛": "yêu",
    "爱": "yêu",
    "創": "tạo",
    "创": "tạo",
    "貼": "dán sát",
    "贴": "dán sát",
    "摧": "phá hủy",
    "囚": "tù",
    "葉": "lá",
    "叶": "lá",
    "溫": "ấm",
    "温": "ấm",
    "象": "hình tượng",
    "靜": "tĩnh",
    "静": "tĩnh",
    "願": "nguyện",
    "愿": "nguyện",
    "箱": "hộp",
    "蒙": "che mờ",
    "詳": "chi tiết",
    "详": "chi tiết",
    "操": "thao tác",
    "滅": "diệt",
    "灭": "diệt",
    "仰": "ngửa lên",
    "耀": "rực",
    "負": "chịu",
    "负": "chịu",
    "論": "luận",
    "论": "luận",
    "陣": "trận",
    "阵": "trận",
    "執": "thi hành",
    "执": "thi hành",
    "腰": "eo",
    "組": "nhóm",
    "组": "nhóm",
    "休": "nghỉ",
    "漢": "Hán",
    "汉": "Hán",
    "補": "bổ",
    "补": "bổ",
    "牧": "mục",
    "勒": "Le",
    "待": "chờ",
    "盔": "mũ giáp",
    "瞬": "chớp mắt",
    "納": "nạp",
    "纳": "nạp",
    "招": "chiêu",
    "途": "đường",
    "音": "âm",
    "公": "công",
    "輾": "lăn",
    "辘": "lọc cọc",
    "誰": "ai",
    "谁": "ai",
    "敏": "nhạy",
    "誤": "nhầm",
    "误": "nhầm",
    "塞": "nhét",
    "腹": "bụng",
    "採": "hái",
    "采": "hái",
    "費": "phí",
    "费": "phí",
    "推": "đẩy",
    "膏": "cao",
    "糙": "thô ráp",
    "揮": "vung",
    "挥": "vung",
    "激": "kích động",
    "恆": "hằng",
    "恒": "hằng",
    "潛": "tiềm",
    "潜": "tiềm",
    "猛": "mạnh bạo",
    "髒": "bẩn",
    "脏": "bẩn",
    "誓": "thề",
    "踏": "đạp",
    "懂": "hiểu",
    "填": "lấp",
    "擦": "chà",
    "盯": "nhìn chằm chằm",
    "醒": "tỉnh",
    "菲": "Phi",
    "盜": "trộm",
    "盗": "trộm",
    "堆": "đống",
    "露": "lộ",
    "砸": "đập",
    "假": "giả",
    "漫": "lan",
    "勇": "dũng cảm",
    "斬": "chém",
    "斩": "chém",
    "疊": "chồng",
    "叠": "chồng",
    "疼": "đau",
    "又": "lại",
    "融": "tan hòa",
    "側": "bên",
    "侧": "bên",
    "擾": "quấy",
    "扰": "quấy",
    "勝": "thắng",
    "胜": "thắng",
    "翻": "lật",
    "獻": "dâng",
    "献": "dâng",
    "矛": "giáo",
    "養": "nuôi",
    "养": "nuôi",
    "獄": "ngục",
    "狱": "ngục",
    "庇": "che chở",
    "犬": "chó",
    "蒼": "xanh xám",
    "苍": "xanh xám",
    "捷": "nhanh",
    "頓": "bỗng",
    "顿": "bỗng",
    "松": "lỏng",
    "鋼": "thép",
    "钢": "thép",
    "審": "xét",
    "审": "xét",
    "隙": "khe hở",
    "蓄": "tích trữ",
    "慣": "quen",
    "惯": "quen",
    "拆": "tháo",
    "畸": "dị dạng",
    "姿": "dáng vẻ",
    "堪": "chịu nổi",
    "撿": "nhặt",
    "捡": "nhặt",
    "耐": "chịu đựng",
    "版": "bản",
    "銅": "đồng",
    "铜": "đồng",
    "龐": "khổng lồ",
    "庞": "khổng lồ",
    "粉": "bột",
    "擺": "bày",
    "摆": "bày",
    "焦": "cháy sém",
    "擔": "gánh",
    "担": "gánh",
    "探": "thăm dò",
    "伙": "bọn",
    "眾": "đám đông",
    "众": "đám đông",
    "劫": "cướp",
    "貌": "diện mạo",
    "識": "hiểu biết",
    "识": "hiểu biết",
    "析": "phân tích",
    "朽": "mục nát",
    "削": "gọt",
    "劈": "bổ",
    "契": "khế ước",
    "寄": "gửi",
    "譜": "phổ",
    "谱": "phổ",
    "症": "chứng",
    "移": "di chuyển",
    "讀": "đọc",
    "读": "đọc",
    "臉": "mặt",
    "脸": "mặt",
    "宗": "tông",
    "尾": "đuôi",
    "圈": "vòng",
    "趕": "đuổi",
    "赶": "đuổi",
    "胡": "nhảm",
    "拔": "nhổ",
    "際": "giữa",
    "际": "giữa",
    "詩": "thơ",
    "诗": "thơ",
    "另": "khác",
    "褲": "quần",
    "裤": "quần",
    "號": "hiệu",
    "号": "hiệu",
    "偉": "vĩ đại",
    "伟": "vĩ đại",
    "屠": "tàn sát",
    "聰": "thông minh",
    "聪": "thông minh",
})

CHARMAP.update({
    "夜": "đêm",
    "影": "bóng",
    "沉": "chìm",
    "刺": "đâm",
    "池": "ao",
    "超": "vượt",
    "烈": "dữ dội",
    "怒": "giận",
    "退": "lùi",
    "衡": "cân",
    "永": "vĩnh",
    "送": "đưa",
    "詭": "quỷ quyệt",
    "诡": "quỷ quyệt",
    "魔": "ma",
    "早": "sớm",
    "壞": "xấu",
    "坏": "xấu",
    "哪": "đâu",
    "跟": "theo",
    "固": "cố định",
    "必": "bắt buộc",
    "室": "phòng",
    "零": "không",
    "排": "xếp",
    "肩": "vai",
    "陷": "rơi vào",
    "巧": "khéo",
    "迎": "đón",
    "咬": "cắn",
    "毛": "lông",
    "屍": "xác",
    "尸": "xác",
    "善": "thiện",
    "拿": "cầm",
    "輩": "hạng người",
    "辈": "hạng người",
    "茫": "mênh mông",
    "驅": "xua",
    "驱": "xua",
    "藝": "nghệ",
    "艺": "nghệ",
    "堂": "sảnh",
    "便": "liền",
    "劃": "vạch",
    "划": "vạch",
    "蓋": "che",
    "盖": "che",
    "坑": "hố",
    "遇": "gặp",
    "鑄": "đúc",
    "铸": "đúc",
    "憑": "dựa",
    "凭": "dựa",
    "跳": "nhảy",
    "典": "điển",
    "考": "khảo",
    "陰": "âm",
    "阴": "âm",
    "踩": "giẫm",
    "泥": "bùn",
    "借": "mượn",
    "滑": "trơn",
    "遮": "che",
    "宛": "tựa như",
    "普": "phổ thông",
    "竟": "rốt cuộc",
    "擅": "giỏi",
    "喜": "thích",
    "素": "tố",
    "袋": "túi",
    "慘": "thảm",
    "惨": "thảm",
    "瀕": "sắp",
    "濒": "sắp",
    "淪": "sa vào",
    "沦": "sa vào",
    "渴": "khát",
    "功": "công",
    "末": "cuối",
    "拯": "cứu",
    "隔": "ngăn cách",
    "砍": "chém",
    "袖": "tay áo",
    "鑽": "khoan",
    "钻": "khoan",
    "批": "lô",
    "韌": "dẻo dai",
    "韧": "dẻo dai",
    "倍": "gấp",
    "押": "áp giải",
    "抓": "bắt",
    "雲": "mây",
    "云": "mây",
    "宿": "ngủ lại",
    "希": "hy vọng",
    "潮": "triều",
    "捕": "bắt",
    "歷": "trải qua",
    "历": "trải qua",
    "扛": "gánh chịu",
    "挑": "chọn",
    "允": "cho phép",
    "佳": "tốt đẹp",
    "烤": "nướng",
    "織": "dệt",
    "织": "dệt",
    "搖": "lắc",
    "摇": "lắc",
    "酸": "chua",
    "罕": "hiếm",
    "遭": "gặp phải",
    "鼠": "chuột",
    "喘": "thở dốc",
    "寬": "rộng",
    "宽": "rộng",
    "潔": "sạch",
    "洁": "sạch",
    "綻": "nở bung",
    "绽": "nở bung",
    "份": "phần",
    "譽": "danh dự",
    "誉": "danh dự",
    "悲": "buồn",
    "略": "hơi",
    "掩": "che giấu",
    "伴": "bạn đồng hành",
    "免": "miễn",
    "扭": "vặn",
    "遲": "chậm",
    "迟": "chậm",
    "臭": "hôi",
    "逆": "ngược",
    "封": "phong kín",
    "妄": "ngông cuồng",
    "尊": "tôn kính",
    "句": "câu",
    "倫": "luân",
    "伦": "luân",
    "演": "diễn",
    "透": "xuyên thấu",
    "剖": "mổ xẻ",
    "挨": "chịu",
    "賭": "cược",
    "赌": "cược",
    "健": "khỏe",
    "滴": "giọt",
    "呆": "ngây",
    "舉": "nêu",
    "举": "nêu",
    "晉": "Tấn",
    "晋": "Tấn",
    "勉": "cố gắng",
    "陋": "tồi tàn",
    "培": "vun trồng",
    "售": "bán",
    "驛": "trạm dịch",
    "驿": "trạm dịch",
    "舒": "thoải mái",
    "迅": "nhanh",
    "榨": "vắt ép",
    "您": "ngài",
    "政": "chính sự",
    "良": "tốt",
    "刮": "cạo",
    "否": "không",
    "鍵": "phím",
    "键": "phím",
    "橫": "ngang",
    "横": "ngang",
    "繼": "tiếp",
    "继": "tiếp",
    "鬼": "quỷ",
    "騙": "lừa",
    "骗": "lừa",
    "災": "tai họa",
    "灾": "tai họa",
    "科": "khoa",
    "七": "bảy",
    "浮": "nổi",
    "百": "trăm",
    "頸": "cổ",
    "颈": "cổ",
    "碼": "mã",
    "码": "mã",
    "君": "quân",
    "燃": "cháy",
    "盲": "mù",
    "銘": "khắc tên",
    "铭": "khắc tên",
    "喪": "mất",
    "丧": "mất",
    "震": "chấn động",
    "印": "dấu",
    "猶": "vẫn còn",
    "犹": "vẫn còn",
    "屈": "khuất nhục",
    "廝": "chém giết",
    "厮": "chém giết",
    "扯": "kéo",
    "逼": "ép",
    "促": "thúc",
    "凶": "dữ",
    "吻": "hôn",
    "瓦": "ngói",
    "摸": "sờ",
    "病": "bệnh",
    "妙": "kỳ diệu",
    "顱": "sọ",
    "颅": "sọ",
    "伐": "bước",
    "紙": "giấy",
    "纸": "giấy",
    "嬌": "yểu điệu",
    "娇": "yểu điệu",
    "車": "xe",
    "车": "xe",
    "劑": "thuốc",
    "剂": "thuốc",
    "皆": "đều",
    "挖": "đào",
    "厭": "chán",
    "厌": "chán",
    "偽": "giả",
    "伪": "giả",
    "跨": "vượt qua",
    "鱗": "vảy",
    "鳞": "vảy",
    "買": "mua",
    "买": "mua",
    "彼": "kia",
    "蹲": "ngồi xổm",
    "怎": "thế nào",
    "洗": "rửa",
    "兒": "nhi",
    "儿": "nhi",
    "彎": "cong",
    "弯": "cong",
    "掛": "treo",
    "挂": "treo",
    "鉤": "móc",
    "钩": "móc",
    "撞": "va",
    "煉": "luyện",
    "炼": "luyện",
    "純": "thuần",
    "纯": "thuần",
    "圓": "tròn",
    "圆": "tròn",
    "昏": "choáng",
    "燈": "đèn",
    "灯": "đèn",
    "華": "hoa lệ",
    "华": "hoa lệ",
    "搶": "cướp",
    "抢": "cướp",
    "顧": "lo nghĩ",
    "顾": "lo nghĩ",
    "凡": "phàm",
    "捲": "cuốn",
    "卷": "cuốn",
    "付": "trả",
    "扣": "trừ",
    "砂": "cát thô",
    "屏": "màn hình",
    "頻": "tần suất",
    "频": "tần suất",
    "叢": "bụi",
    "丛": "bụi",
    "列": "hàng",
    "牌": "thẻ",
    "裹": "bọc",
    "敬": "kính",
    "胞": "bào",
    "腕": "cổ tay",
    "忘": "quên",
    "宣": "tuyên",
    "魄": "phách",
    "碰": "va chạm",
    "敢": "dám",
    "累": "mệt",
    "蹤": "dấu vết",
    "踪": "dấu vết",
    "爪": "móng vuốt",
    "悚": "rùng mình",
    "龜": "rùa",
    "龟": "rùa",
    "纏": "quấn",
    "缠": "quấn",
    "絞": "xoắn",
    "绞": "xoắn",
    "脊": "xương sống",
    "鼓": "trống",
    "絆": "vướng",
    "绊": "vướng",
    "搞": "làm loạn",
    "察": "xem xét",
    "亮": "sáng",
    "悟": "ngộ",
    "糟": "tệ",
    "紋": "hoa văn",
    "纹": "hoa văn",
    "楚": "Sở",
    "役": "dịch",
    "私": "riêng",
    "淺": "nông",
    "浅": "nông",
    "嗎": "không",
    "吗": "không",
    "牙": "răng",
    "洞": "hang",
    "旁": "bên cạnh",
    "燒": "đốt",
    "烧": "đốt",
    "街": "phố",
    "寂": "lặng",
    "均": "đều",
    "爬": "bò",
    "鄉": "quê",
    "乡": "quê",
    "佩": "đeo",
    "歲": "tuổi",
    "岁": "tuổi",
    "囊": "túi",
    "鯊": "cá mập",
    "鲨": "cá mập",
    "軟": "mềm",
    "软": "mềm",
    "淌": "chảy",
})

CHARMAP.update({
    "署": "sở",
    "叉": "nĩa",
    "碾": "nghiền",
    "釀": "ủ",
    "酿": "ủ",
    "盆": "chậu",
    "樓": "lầu",
    "楼": "lầu",
    "芯": "lõi",
    "錢": "tiền",
    "钱": "tiền",
    "傭": "làm thuê",
    "佣": "làm thuê",
    "躍": "nhảy vọt",
    "跃": "nhảy vọt",
    "穴": "hang",
    "濱": "ven bờ",
    "滨": "ven bờ",
    "闖": "xông vào",
    "闯": "xông vào",
    "踞": "chiếm cứ",
    "蛋": "trứng",
    "母": "mẹ",
    "涉": "băng qua",
    "淡": "nhạt",
    "既": "đã",
    "登": "leo lên",
    "釘": "đinh",
    "钉": "đinh",
    "袍": "áo choàng",
    "宰": "giết mổ",
    "掃": "quét",
    "扫": "quét",
    "吐": "nôn",
    "忽": "chợt",
    "狠": "tàn nhẫn",
    "針": "kim",
    "针": "kim",
    "拖": "kéo lê",
    "旋": "xoay",
    "校": "hiệu chỉnh",
    "纖": "mảnh",
    "纤": "mảnh",
    "脹": "sưng",
    "胀": "sưng",
    "彈": "đạn",
    "弹": "đạn",
    "肋": "xương sườn",
    "旦": "một khi",
    "縮": "co lại",
    "缩": "co lại",
    "躁": "bồn chồn",
    "社": "xã",
    "礙": "cản",
    "碍": "cản",
    "晰": "rõ",
    "污": "bẩn",
    "儀": "nghi thức",
    "仪": "nghi thức",
    "賴": "ỷ lại",
    "赖": "ỷ lại",
    "稍": "hơi",
    "惑": "mê hoặc",
    "摔": "ngã",
    "旗": "cờ",
    "懷": "ôm lòng",
    "怀": "ôm lòng",
    "抖": "run",
    "波": "sóng",
    "憶": "ký ức",
    "忆": "ký ức",
    "毆": "đánh",
    "殴": "đánh",
    "贏": "thắng",
    "赢": "thắng",
    "返": "quay về",
    "寒": "lạnh",
    "吞": "nuốt",
    "己": "mình",
    "述": "thuật lại",
    "律": "luật",
    "刷": "quét",
    "憐": "thương",
    "怜": "thương",
    "奔": "lao đi",
    "冥": "mờ tối",
    "傾": "nghiêng",
    "倾": "nghiêng",
    "議": "nghị",
    "议": "nghị",
    "糊": "hồ",
    "染": "nhuộm",
    "青": "xanh",
    "渾": "đục",
    "浑": "đục",
    "吉": "cát lành",
    "墜": "rơi",
    "坠": "rơi",
    "霉": "mốc",
    "撫": "vuốt ve",
    "抚": "vuốt ve",
    "哦": "ồ",
    "幼": "non trẻ",
    "六": "sáu",
    "催": "thúc",
    "駝": "thồ",
    "驼": "thồ",
    "峻": "dốc đứng",
    "煌": "rực rỡ",
    "趾": "ngón chân",
    "戶": "hộ",
    "户": "hộ",
    "呼": "gọi",
    "序": "thứ tự",
    "盧": "Lu",
    "卢": "Lu",
    "阻": "cản",
    "掘": "đào",
    "撐": "chống đỡ",
    "撑": "chống đỡ",
    "拋": "ném bỏ",
    "抛": "ném bỏ",
    "潤": "ẩm",
    "润": "ẩm",
    "廉": "liêm",
    "含": "chứa",
    "張": "giương",
    "张": "giương",
    "枷": "gông",
    "巷": "ngõ",
    "銷": "tiêu thụ",
    "销": "tiêu thụ",
    "胃": "dạ dày",
    "策": "kế sách",
    "漂": "trôi",
    "寶": "báu",
    "宝": "báu",
    "瀉": "chảy xiết",
    "泻": "chảy xiết",
    "辛": "cay đắng",
    "隕": "rơi",
    "陨": "rơi",
    "峭": "dốc",
    "擲": "ném",
    "掷": "ném",
    "匠": "thợ",
    "牛": "bò",
    "鷹": "ưng",
    "鹰": "ưng",
    "鏡": "gương",
    "镜": "gương",
    "繭": "kén",
    "茧": "kén",
    "焰": "ngọn lửa",
    "剎": "sát-na",
    "刹": "sát-na",
    "寧": "yên",
    "宁": "yên",
    "予": "cho",
    "吼": "gầm",
    "截": "chặn",
    "僻": "hẻo lánh",
    "嚇": "dọa",
    "吓": "dọa",
    "髓": "tủy",
    "舞": "múa",
    "塑": "nặn",
    "懼": "sợ",
    "惧": "sợ",
    "噬": "cắn nuốt",
    "寸": "tấc",
    "撲": "lao vào",
    "扑": "lao vào",
    "兀": "trơ trọi",
    "芽": "mầm",
    "啃": "gặm",
    "垮": "sụp",
    "癖": "thói nghiện",
    "貴": "quý",
    "贵": "quý",
    "懾": "khiếp sợ",
    "慑": "khiếp sợ",
    "熟": "quen",
    "朋": "bạn",
    "嚼": "nhai",
    "肯": "chịu",
    "僵": "cứng đờ",
    "醉": "say",
    "幅": "bức",
    "忌": "kỵ",
    "蕪": "hoang vu",
    "芜": "hoang vu",
    "駁": "loang lổ",
    "驳": "loang lổ",
    "勳": "huân",
    "勋": "huân",
    "描": "miêu",
    "諸": "các",
    "诸": "các",
    "喚": "gọi",
    "唤": "gọi",
    "五": "năm",
    "諾": "hứa",
    "诺": "hứa",
    "辨": "phân biệt",
    "躺": "nằm",
    "桶": "thùng",
    "竭": "cạn kiệt",
    "賦": "ban",
    "赋": "ban",
    "舌": "lưỡi",
    "吹": "thổi",
    "嚥": "nuốt",
    "咽": "nuốt",
    "甘": "ngọt",
    "球": "cầu",
    "禮": "lễ",
    "礼": "lễ",
    "歧": "ngã rẽ",
    "泛": "lan",
    "晚": "tối",
    "歇": "nghỉ",
    "助": "giúp",
    "唾": "nước bọt",
    "乖": "ngoan",
    "歸": "quay về",
    "归": "quay về",
    "傑": "kiệt",
    "杰": "kiệt",
    "芒": "ánh nhọn",
    "衷": "tận đáy lòng",
    "鳴": "kêu",
    "鸣": "kêu",
    "訴": "kể",
    "诉": "kể",
    "塌": "sụp",
    "釋": "giải thích",
    "释": "giải thích",
    "丢": "vứt",
    "史": "sử",
    "紛": "rối rắm",
    "纷": "rối rắm",
    "拓": "khai phá",
    "馱": "chở thồ",
    "驮": "chở thồ",
    "鹹": "mặn",
    "咸": "mặn",
    "違": "trái",
    "违": "trái",
    "艘": "chiếc tàu",
    "股": "luồng",
    "燥": "khô",
    "闊": "rộng",
    "阔": "rộng",
    "蝕": "ăn mòn",
    "蚀": "ăn mòn",
    "泰": "thái",
    "奢": "xa xỉ",
    "抱": "ôm",
    "萎": "héo",
    "耕": "cày",
    "攝": "thu vào",
    "摄": "thu vào",
    "雄": "hùng",
    "鑒": "soi xét",
    "鉴": "soi xét",
    "沾": "dính",
    "緝": "truy bắt",
    "缉": "truy bắt",
    "苟": "tạm bợ",
    "擴": "mở rộng",
    "扩": "mở rộng",
    "剿": "tiễu trừ",
    "羅": "La",
    "罗": "La",
    "祖": "tổ",
    "氏": "thị",
    "蔣": "Tưởng",
    "蒋": "Tưởng",
    "鄰": "láng giềng",
    "邻": "láng giềng",
    "旱": "khô hạn",
    "琳": "Lin",
})

CHARMAP.update({
    "箭": "mũi tên",
    "畜": "gia súc",
    "濃": "đậm đặc",
    "浓": "đậm đặc",
    "廠": "xưởng",
    "厂": "xưởng",
    "棚": "lán",
    "搭": "dựng",
    "鬧": "ồn",
    "闹": "ồn",
    "貨": "hàng",
    "货": "hàng",
    "鋪": "tiệm",
    "铺": "tiệm",
    "床": "giường",
    "賺": "kiếm lời",
    "赚": "kiếm lời",
    "綁": "trói",
    "绑": "trói",
    "焊": "hàn",
    "枚": "miếng",
    "眉": "mày",
    "軌": "đường ray",
    "轨": "đường ray",
    "僧": "tăng",
    "絡": "mạng lưới",
    "络": "mạng lưới",
    "符": "ký hiệu",
    "摩": "ma sát",
    "逐": "đuổi theo",
    "脖": "cổ",
    "齒": "răng",
    "齿": "răng",
    "炎": "lửa viêm",
    "雕": "khắc",
    "愉": "vui vẻ",
    "抑": "kìm nén",
    "振": "rung",
    "顫": "run",
    "颤": "run",
    "卸": "tháo xuống",
    "斜": "nghiêng",
    "黎": "bình minh",
    "奏": "tấu",
    "烙": "đóng dấu bỏng",
    "謊": "lời dối",
    "谎": "lời dối",
    "撼": "lay động",
    "萬": "vạn",
    "万": "vạn",
    "投": "ném",
    "陽": "dương",
    "阳": "dương",
    "灼": "thiêu",
    "噩": "ác mộng",
    "謀": "mưu",
    "谋": "mưu",
    "臣": "thần tử",
    "慧": "tuệ",
    "諳": "am hiểu",
    "谙": "am hiểu",
    "講": "nói",
    "讲": "nói",
    "膠": "keo",
    "胶": "keo",
    "譯": "dịch",
    "译": "dịch",
    "哀": "ai oán",
    "省": "tỉnh",
    "腫": "sưng",
    "肿": "sưng",
    "駭": "kinh hãi",
    "骇": "kinh hãi",
    "猩": "khỉ đột",
    "銳": "sắc",
    "锐": "sắc",
    "蟄": "ngủ đông",
    "蛰": "ngủ đông",
    "餅": "bánh",
    "饼": "bánh",
    "糖": "đường",
    "伸": "duỗi",
    "喊": "hét",
    "飽": "no",
    "饱": "no",
    "癡": "si mê",
    "痴": "si mê",
    "慌": "hoảng",
    "炫": "khoe",
    "歌": "bài ca",
    "談": "nói chuyện",
    "谈": "nói chuyện",
    "桌": "bàn",
    "癮": "nghiện",
    "瘾": "nghiện",
    "烏": "đen",
    "乌": "đen",
    "誕": "đản sinh",
    "诞": "đản sinh",
    "莫": "chớ",
    "飄": "trôi nổi",
    "飘": "trôi nổi",
    "趣": "thú vị",
    "鐘": "chuông",
    "钟": "chuông",
    "討": "thảo luận",
    "讨": "thảo luận",
    "鹽": "muối",
    "盐": "muối",
    "寡": "ít ỏi",
    "膽": "gan mật",
    "胆": "gan mật",
    "摯": "chân thành",
    "挚": "chân thành",
    "赴": "đi tới",
    "忠": "trung thành",
    "窺": "nhìn trộm",
    "窥": "nhìn trộm",
    "嗅": "ngửi",
    "澀": "chát",
    "涩": "chát",
    "販": "buôn bán",
    "贩": "buôn bán",
    "財": "tài sản",
    "财": "tài sản",
    "抬": "nhấc",
    "靶": "bia ngắm",
    "撬": "nạy",
    "漆": "sơn",
    "睡": "ngủ",
    "籍": "sổ sách",
    "瞎": "mù quáng",
    "插": "cắm",
    "幽": "u tịch",
    "漲": "dâng",
    "涨": "dâng",
    "謎": "bí ẩn",
    "谜": "bí ẩn",
    "煽": "xúi giục",
    "暈": "choáng",
    "晕": "choáng",
    "霸": "bá đạo",
    "遙": "xa",
    "遥": "xa",
    "氛": "bầu khí",
    "悄": "lặng lẽ",
    "湯": "canh",
    "汤": "canh",
    "饒": "tha",
    "饶": "tha",
    "湊": "góp lại",
    "凑": "góp lại",
    "掙": "vùng vẫy",
    "挣": "vùng vẫy",
    "忙": "bận",
    "豐": "phong phú",
    "丰": "phong phú",
    "剪": "cắt",
    "壘": "lũy",
    "垒": "lũy",
    "攢": "gom góp",
    "攒": "gom góp",
    "謝": "tạ",
    "谢": "tạ",
    "肥": "béo",
    "羊": "cừu",
    "油": "dầu",
    "鄙": "thô bỉ",
    "顆": "viên",
    "颗": "viên",
    "掉": "rơi",
    "逝": "trôi qua",
    "殆": "gần như",
    "邦": "bang",
    "巫": "phù thủy",
    "窒": "ngạt",
    "懦": "hèn nhát",
    "呢": "nhỉ",
    "嶄": "mới tinh",
    "崭": "mới tinh",
    "疏": "thưa",
    "延": "kéo dài",
    "赤": "đỏ thẫm",
    "梁": "xà",
    "鼬": "chồn",
    "匯": "hội tụ",
    "汇": "hội tụ",
    "矗": "sừng sững",
    "廣": "rộng",
    "广": "rộng",
    "馴": "thuần",
    "驯": "thuần",
    "曲": "cong",
    "獅": "sư tử",
    "狮": "sư tử",
    "狐": "cáo",
    "喝": "uống",
    "搏": "vật lộn",
    "肚": "bụng",
    "幕": "màn",
    "灌": "rót",
    "惹": "chọc",
    "慮": "lo nghĩ",
    "虑": "lo nghĩ",
    "灘": "bãi",
    "滩": "bãi",
    "睜": "mở mắt",
    "睁": "mở mắt",
    "兜": "túi bọc",
    "鞭": "roi",
    "祝": "chúc phúc",
    "哇": "oa",
    "英": "anh hùng",
    "捏": "nắn",
    "靴": "ủng",
    "授": "trao",
    "麟": "lân",
    "帽": "mũ",
    "彥": "hiền tài",
    "彦": "hiền tài",
    "革": "da thuộc",
    "院": "viện",
    "惕": "cảnh giác",
})

CHARMAP.update({
    "三": "ba",
    "花": "hoa",
    "草": "cỏ",
    "千": "ngàn",
    "漁": "đánh cá",
    "渔": "đánh cá",
    "木": "gỗ",
    "束": "bó buộc",
    "男": "nam",
    "井": "giếng",
    "鞣": "thuộc da",
    "廳": "sảnh",
    "厅": "sảnh",
    "閥": "môn phiệt",
    "阀": "môn phiệt",
    "攤": "quầy",
    "摊": "quầy",
    "壟": "luống",
    "垄": "luống",
    "席": "chiếu",
    "慰": "an ủi",
    "香": "thơm",
    "亨": "hanh thông",
    "舜": "Thuấn",
    "宜": "phù hợp",
    "概": "khái quát",
    "樞": "then chốt",
    "枢": "then chốt",
    "濫": "tràn lan",
    "滥": "tràn lan",
    "鍔": "lưỡi chắn",
    "锷": "lưỡi chắn",
    "九": "chín",
    "委": "ủy thác",
    "摘": "hái",
    "懲": "trừng phạt",
    "惩": "trừng phạt",
    "俗": "thô tục",
    "盈": "đầy",
    "晨": "sáng sớm",
    "竹": "tre",
    "汲": "múc nước",
    "綿": "miên man",
    "绵": "miên man",
    "巔": "đỉnh",
    "巅": "đỉnh",
    "浴": "tắm",
    "脾": "lá lách",
    "魘": "ác mộng",
    "魇": "ác mộng",
    "循": "tuân theo",
    "蛇": "rắn",
    "積": "tích",
    "积": "tích",
    "漏": "rò rỉ",
    "播": "gieo phát",
    "挪": "dịch chuyển",
    "拍": "vỗ",
    "扳": "bẻ",
    "匹": "con",
    "嘔": "nôn",
    "呕": "nôn",
    "朝": "triều",
    "隆": "long trọng",
    "腋": "nách",
    "湧": "tuôn trào",
    "涌": "tuôn trào",
    "豫": "do dự",
    "朵": "đóa",
    "淋": "dội",
    "玻": "pha lê",
    "璃": "lưu ly",
    "夷": "man di",
    "騰": "bốc lên",
    "腾": "bốc lên",
    "掄": "vung tròn",
    "抡": "vung tròn",
    "霜": "sương giá",
    "禽": "chim thú",
    "撈": "vớt",
    "捞": "vớt",
    "晃": "lắc lư",
    "羽": "lông vũ",
    "燕": "yến",
    "驟": "đột ngột",
    "骤": "đột ngột",
    "距": "khoảng cách",
    "娼": "kỹ nữ",
    "羞": "xấu hổ",
    "恥": "nhục",
    "耻": "nhục",
    "競": "tranh",
    "竞": "tranh",
    "焚": "đốt cháy",
    "攫": "chộp",
    "啖": "ăn",
    "魅": "mị",
    "秒": "giây",
    "卓": "xuất chúng",
    "壇": "đàn",
    "坛": "đàn",
    "侶": "bạn lữ",
    "侣": "bạn lữ",
    "約": "ước hẹn",
    "约": "ước hẹn",
    "款": "khoản",
    "趁": "nhân lúc",
    "筆": "bút",
    "笔": "bút",
    "凝": "ngưng tụ",
    "踐": "giẫm đạp",
    "践": "giẫm đạp",
    "肆": "tàn phá",
    "癲": "điên",
    "癫": "điên",
    "淚": "nước mắt",
    "泪": "nước mắt",
    "邁": "bước qua",
    "迈": "bước qua",
    "撥": "gạt",
    "拨": "gạt",
    "騷": "quấy nhiễu",
    "骚": "quấy nhiễu",
    "弦": "dây đàn",
    "嘆": "than",
    "叹": "than",
    "趟": "chuyến",
    "吵": "ồn ào",
    "腸": "ruột",
    "肠": "ruột",
    "傻": "ngốc",
    "哄": "dỗ",
    "噴": "phun",
    "喷": "phun",
    "匕": "dao găm",
    "炸": "nổ",
    "賽": "thi đấu",
    "赛": "thi đấu",
    "悶": "ngột ngạt",
    "闷": "ngột ngạt",
    "暢": "thông suốt",
    "畅": "thông suốt",
    "興": "hưng",
    "兴": "hưng",
    "扶": "đỡ",
    "泡": "bọt",
    "顏": "mặt mũi",
    "颜": "mặt mũi",
    "錚": "leng keng",
    "铮": "leng keng",
    "栗": "run sợ",
    "笑": "cười",
    "博": "đánh cược",
    "跪": "quỳ",
    "仔": "con nhỏ",
    "溜": "lẻn",
    "歪": "lệch",
    "弄": "làm",
    "濺": "bắn tóe",
    "溅": "bắn tóe",
    "癟": "xẹp",
    "瘪": "xẹp",
    "鉚": "tán đinh",
    "铆": "tán đinh",
    "扔": "ném đi",
    "缽": "bát",
    "钵": "bát",
    "凱": "khải hoàn",
    "凯": "khải hoàn",
    "罵": "mắng",
    "骂": "mắng",
    "魯": "thô lỗ",
    "鲁": "thô lỗ",
    "膩": "ngấy",
    "腻": "ngấy",
    "敞": "mở rộng",
    "疤": "sẹo",
    "溝": "rãnh",
    "沟": "rãnh",
    "洩": "tiết ra",
    "泄": "tiết ra",
    "縱": "dọc",
    "纵": "dọc",
    "煩": "phiền",
    "烦": "phiền",
    "嵌": "khảm",
    "荏": "trôi qua",
    "苒": "lặng lẽ trôi",
    "艱": "gian nan",
    "艰": "gian nan",
    "抉": "móc ra",
    "鐧": "giản",
    "锏": "giản",
    "施": "thi hành",
    "攜": "mang theo",
    "携": "mang theo",
    "牽": "dắt",
    "牵": "dắt",
    "恨": "hận",
    "孩": "đứa trẻ",
    "悔": "hối hận",
    "稅": "thuế",
    "税": "thuế",
    "肺": "phổi",
    "扼": "bóp nghẹt",
    "狹": "hẹp",
    "狭": "hẹp",
    "迪": "Di",
    "垣": "tường thấp",
    "舟": "thuyền",
    "苛": "hà khắc",
    "漉": "ướt sũng",
    "黢": "đen nhẻm",
    "銀": "bạc",
    "银": "bạc",
    "庸": "tầm thường",
    "飾": "trang sức",
    "饰": "trang sức",
    "墮": "sa đọa",
    "堕": "sa đọa",
    "頑": "cứng đầu",
    "顽": "cứng đầu",
    "佬": "gã",
    "瘦": "gầy",
    "炮": "pháo",
    "泳": "bơi",
    "診": "chẩn đoán",
    "诊": "chẩn đoán",
    "拙": "vụng",
    "蹭": "cọ ké",
    "悠": "thong thả",
    "愣": "sững sờ",
    "米": "gạo",
    "刑": "hình phạt",
    "膨": "phồng",
    "仙": "tiên",
    "舔": "liếm",
    "綜": "tổng hợp",
    "综": "tổng hợp",
    "簷": "mái hiên",
    "檐": "mái hiên",
    "掏": "móc ra",
    "辦": "làm",
    "办": "làm",
    "鉸": "cắt bằng kéo",
    "铰": "cắt bằng kéo",
    "擎": "giơ cao",
    "惟": "duy",
    "嘎": "két",
    "卵": "trứng",
    "豎": "dựng đứng",
    "竖": "dựng đứng",
    "嗶": "bíp",
    "哔": "bíp",
    "啵": "bo",
    "歐": "Âu",
    "欧": "Âu",
    "嘯": "hú",
    "啸": "hú",
    "禿": "trọc",
    "秃": "trọc",
    "竄": "chạy trốn",
    "窜": "chạy trốn",
    "享": "hưởng",
    "逸": "an nhàn",
    "癱": "liệt",
    "瘫": "liệt",
    "眈": "nhìn chằm chằm",
    "崇": "sùng bái",
    "穢": "ô uế",
    "秽": "ô uế",
    "嗚": "ô ô",
    "呜": "ô ô",
    "詡": "khoe khoang",
    "诩": "khoe khoang",
    "姆": "mẫu",
    "甸": "đồng nội",
    "厲": "dữ dằn",
    "厉": "dữ dằn",
    "佇": "đứng chờ",
    "伫": "đứng chờ",
    "瘤": "u bướu",
    "呈": "trình ra",
    "鐐": "xiềng",
    "镣": "xiềng",
    "丁": "đinh",
    "債": "nợ",
    "债": "nợ",
    "怨": "oán",
    "援": "viện trợ",
    "洲": "châu",
    "謂": "gọi là",
    "谓": "gọi là",
    "萊": "Lai",
    "莱": "Lai",
    "富": "giàu",
    "奎": "Khuê",
    "彩": "màu sắc",
    "虹": "cầu vồng",
    "蘇": "Tô",
    "苏": "Tô",
    "貧": "nghèo",
    "贫": "nghèo",
    "濟": "cứu giúp",
    "济": "cứu giúp",
    "瑜": "ngọc đẹp",
    "瓜": "dưa",
    "召": "triệu tập",
    "聊": "trò chuyện",
    "框": "khung",
    "梯": "thang",
    "僕": "tôi tớ",
    "仆": "tôi tớ",
    "沌": "hỗn độn",
    "疾": "bệnh nhanh",
    "柱": "cột",
    "瑞": "điềm lành",
    "職": "chức",
    "职": "chức",
    "曹": "Tào",
    "丕": "Phi",
    "嘻": "hi hi",
    "訪": "thăm hỏi",
    "访": "thăm hỏi",
    "戈": "giáo mác",
    "淹": "ngập",
    "祥": "cát tường",
    "簍": "sọt",
    "篓": "sọt",
    "墓": "mộ",
})


def main() -> None:
    for path in BASE.glob("*/index.vi.html"):
        source_path = path.with_name("source.zh.html")
        text = source_path.read_text(encoding="utf-8") if source_path.exists() else path.read_text(encoding="utf-8")
        for src, dst in PHRASE_FIXES.items():
            text = text.replace(src, dst)
        for src, dst in COMMON.items():
            text = text.replace(src, dst)
        for src, dst in EXTRA.items():
            text = text.replace(src, dst)
        for src, dst in CHARMAP.items():
            text = text.replace(src, dst)
        text = text.replace("待khởi tạo", "chờ khởi tạo")
        text = text.replace("所处khu vực", "khu vực đang ở")
        text = text.replace("暂无Mô tả", "chưa có mô tả")
        text = text.replace("暂无Thành viên", "chưa có thành viên")
        text = text.replace("暂无chủ lực", "chưa có chủ lực")
        text = text.replace("nhân vật数据待khởi tạo", "dữ liệu nhân vật chờ khởi tạo")
        text = text.replace("暂无Mô tả ngoại hình", "chưa có mô tả ngoại hình")
        text = text.replace("chính面hiệu quả", "hiệu quả tích cực")
        text = text.replace("负面hiệu quả", "hiệu quả tiêu cực")
        text = text.replace("tạmKhông đăng ký công trình", "tạm không đăng ký công trình")
        text = text.replace("tạmKhông truyền văn", "tạm không có truyền văn")
        text = text.replace("tạmKhông ghi chép", "tạm không có ghi chép")
        text = text.replace("sửa chỉnhThân phận", "sửa thân phận")
        text = text.replace("điểm点击查看Số lần tấn côngquy tắc", "nhấn để xem quy tắc số lần tấn công")
        text = text.replace("điểm点击 sửa按钮编辑玩家Phe phái", "nhấn nút chỉnh sửa để sửa phe phái người chơi")
        text = text.replace("điểm点击 sửa按钮编辑Phe pháiMô tả", "nhấn nút chỉnh sửa để sửa mô tả phe phái")
        text = text.replace("chủ lựcthiết定", "thiết lập chủ lực")
        text = text.replace("tạm thời分 biệt", "tạm thời phân biệt")
        text = text.replace("không thể xóa cứ điểm", "không thể xóa cứ điểm")
        text = text.replace("xóa cứ điểm thế giới sáchThất bại", "xóa cứ điểm thế giới sách thất bại")
        text = text.replace("đồng bộ cứ điểm thế giới sáchThất bại", "đồng bộ cứ điểm thế giới sách thất bại")
        text = text.replace("xây mớicứ điểm", "xây mới cứ điểm")
        text = text.replace("小型哨站", "đồn gác nhỏ")
        text = text.replace("成熟村庄", "làng trưởng thành")
        text = text.replace("城镇级Cứ điểm", "cứ điểm cấp thị trấn")
        text = text.replace("权力中心", "trung tâm quyền lực")
        text = text.replace("主任务Trạng thái", "trạng thái nhiệm vụ chính")
        text = text.replace("暂无传闻", "chưa có truyền văn")
        text = text.replace("未标记số ngày", "chưa đánh dấu số ngày")
        text = text.replace("Gãy xương层数", "tầng gãy xương")
        text = text.replace("解除Gãy xương", "giải trừ gãy xương")
        text = text.replace("没有主要nhân vật", "không có nhân vật chính")
        text = text.replace("没有主要角色", "không có nhân vật chính")
        text = text.replace("kenshitùy chọncột", "Kenshi - Tùy chọn cột")
        text = text.replace("kenshimớiTrạng tháicột", "Kenshi - Trạng thái cột")
        text = text.replace("Kenshi tung xúc xắckiểmđịnh", "Kenshi - Tung xúc xắc kiểm định")
        text = re.sub(r"[\u3400-\u4dbf\u4e00-\u9fff]", "", text)
        path.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
